// Auto-generated topical keyword index used for on-page SEO/AEO content and meta keywords.

export const screenerKeywords: string[] = [
  "stock screener",
  "free stock screener",
  "best stock screener 2026",
  "stock screener India",
  "stock screener USA",
  "stock screener for value investing",
  "stock screener for growth stocks",
  "how to use a stock screener",
  "penny stock screener",
  "screener",
  "intraday screener",
  "finviz screener",
  "mutual fund screener",
  "ticker tape screener",
  "etf screener",
  "tradingview stock screener",
  "tcs screener",
  "crypto screener",
  "itc screener",
  "screener and opioid assessment for patients with pain-revised (soapp-r)",
  "screener and opioid assessment for patients with pain-revised",
  "screener and opioid assessment for patients with pain",
  "screener app",
  "screener ai",
  "screener assessment",
  "screener api",
  "screener all stocks",
  "screener app for ios",
  "screener apk",
  "adhd screener",
  "adani power screener",
  "asian paints screener",
  "articulation screener",
  "autism screener",
  "ashok leyland screener",
  "angel one screener",
  "apollo micro systems screener",
  "ai screener",
  "adani green screener",
  "screener bucket",
  "screener bucket for excavator",
  "screener bucket for skid steer",
  "screener box",
  "screener bse",
  "screener bajaj finance",
  "screener breakout stocks",
  "screener bel",
  "screener block deals",
  "screener bhel",
  "bse screener",
  "best stock screener india",
  "best stock screener",
  "bel screener",
  "bajaj finance screener",
  "bajaj housing finance screener",
  "bse share price screener",
  "bandhan bank screener",
  "breakout stocks screener",
  "bhel screener",
  "screener certification",
  "screener copy",
  "screener call",
  "screener construction",
  "screener chrome extension",
  "screener com",
  "screener cupid",
  "screener chartink",
  "screener crypto",
  "screener canada",
  "chartink screener for intraday",
  "chartink com screener",
  "cdsl screener",
  "chartink screener for swing trading",
  "cams screener",
  "cupid screener",
  "cg power screener",
  "coal india screener",
  "coforge screener",
  "screener dvds",
  "screener definition",
  "screener dirt",
  "screener download",
  "screener dex",
  "screener download for pc",
  "screener data patterns",
  "screener dixon technologies",
  "dex screener",
  "dixon screener",
  "dyslexia screener",
  "desk screener",
  "dirt screener",
  "dex screener app",
  "deck screener",
  "dmart screener",
  "dhan screener",
  "deepak nitrite screener",
  "screener equipment",
  "screener extension",
  "screener excel upload",
  "screener excel",
  "screener etf",
  "screener eternal",
  "screener e2e networks",
  "screener emmvee photovoltaic",
  "screener eicher motors",
  "screener extension for google chrome",
  "eternal screener",
  "etf screener india",
  "e2e networks share price screener",
  "easemytrip screener",
  "exide screener",
  "eternal share price screener",
  "e2e screener",
  "eicher motors screener",
  "eiel screener",
  "screener for us stocks",
  "screener for sale",
  "screener finviz",
  "screener for borderline personality disorder",
  "screener for dirt",
  "screener for ocd",
  "screener for indian stocks",
  "screener for adhd",
  "screener for ptsd",
  "fatafat screener",
  "forex screener",
  "fatafat stock screener",
  "fund screener",
  "flight screener",
  "finviz com stock screener",
  "finology screener",
  "federal bank screener",
  "screener groww",
  "screener google",
  "screener golden crossover",
  "screener ge vernova",
  "screener gravita india",
  "screener genus power",
  "screener grse",
  "screener gmr airport",
  "screener godrej properties",
  "screener gold",
  "groww screener",
  "gucci screener sneakers",
  "google finance stock screener",
  "gucci screener",
  "grse screener",
  "gail screener",
  "gravita screener",
  "groww share price screener",
  "genus power screener",
  "google screener",
  "screener hdfc bank",
  "screener hero",
  "screener heatmap",
  "screener hfcl",
  "screener hire",
  "screener hdfc",
  "screener hul",
  "screener happiest minds",
  "screener hcl tech",
  "screener hal",
  "hdfc bank screener",
  "hdfc screener",
  "health screener jobs",
  "happiest minds screener",
  "hal screener",
  "hfcl screener",
  "halal stock screener",
  "hul screener",
  "health screener",
  "hindustan zinc screener",
  "screener in",
  "screener india",
  "screener interview",
  "screener indian stocks",
  "screener in spanish",
  "screener interview questions",
  "screener itc",
  "screener in screens",
  "screener in porch",
  "screener india stocks",
  "infosys screener",
  "investing com stock screener",
  "idfc first bank screener",
  "ireda screener",
  "iex screener",
  "irfc screener",
  "irctc screener",
  "investing com screener",
  "screener jobs",
  "screener jobs near me",
  "screener job description",
  "screener jio finance",
  "screener job in airport",
  "screener jp power",
  "screener jsw steel",
  "screener jsw energy",
  "screener jyoti cnc",
  "screener jio financial services",
  "jio finance screener",
  "jp power screener",
  "jsw energy screener",
  "jsw cement screener",
  "jsw infra screener",
  "jyothy labs screener",
  "jeena sikho screener",
  "jindal saw screener",
  "jio financial services screener",
  "jio finance share price screener",
  "screener king",
  "screener kaynes technology",
  "screener kalyan jewellers",
  "screener kya hai",
  "screener kpit tech",
  "screener kaynes",
  "screener kec international",
  "screener kpi green",
  "screener kpit",
  "klse screener",
  "kaynes screener",
  "kalyan jewellers screener",
  "kpit screener",
  "kaynes technology screener",
  "kpi green screener",
  "kaynes technology share price screener",
  "kpit share price screener",
  "kfintech screener",
  "karnataka bank screener",
  "screener login",
  "screener link",
  "screener link meaning",
  "screener login free",
  "screener list",
  "screener like website for us stocks",
  "screener like app for us stocks",
  "screener like website for indian stocks",
  "screener lic",
  "screener laurus labs",
  "lic screener",
  "lenskart screener",
  "live open interest screener",
  "laurus labs screener",
  "letrs spelling screener",
  "lg electronics screener",
  "lexercise dyslexia screener",
  "l&t screener",
  "lt foods screener",
  "lemon tree screener",
  "screener meaning",
  "screener machine",
  "screener mutual funds",
  "screener mule",
  "screener mcp",
  "screener meme coin",
  "screener movie",
  "screener meaning film",
  "screener mcx",
  "screener multibagger stocks",
  "momo screener",
  "moschip screener",
  "mcx screener",
  "mutual fund screener india",
  "meesho screener",
  "momentum stocks screener",
  "muthoot finance screener",
  "medical screener",
  "screener navigator",
  "screener nifty 50",
  "screener nse",
  "screener ntpc",
  "screener netweb technologies",
  "screener nmdc",
  "screener nifty",
  "screener netweb",
  "screener nsdl",
  "screener nhpc",
  "nifty 50 screener",
  "nsdl screener",
  "netweb screener",
  "nse screener",
  "newborn hearing screener jobs",
  "nmdc screener",
  "ntpc screener",
  "natco pharma screener",
  "nifty screener",
  "newborn hearing screener",
  "screener of handwriting proficiency",
  "screener on tradingview app",
  "screener operator",
  "screener of handwriting proficiency login",
  "screener online",
  "screener ongc",
  "screener ola electric",
  "screener owner",
  "screener oswal pumps",
  "ola electric screener",
  "ocd screener",
  "ola screener",
  "ongc screener",
  "oswal pumps screener",
  "olectra greentech screener",
  "oriana power screener",
  "ola electric share price screener",
  "ongc share price screener",
  "screener parts",
  "screener position",
  "screener passport",
  "screener penny stocks",
  "screener psx",
  "screener portal",
  "screener premium",
  "screener pine labs",
  "screener pricing",
  "screener pc jewellers",
  "premarket screener",
  "polycab screener",
  "pfc screener",
  "pc jeweller screener",
  "paytm screener",
  "pine screener",
  "pg electroplast screener",
  "premier energies screener",
  "pgel screener",
  "screener questions",
  "screener query",
  "screener questions for interview",
  "screener quarterly results today",
  "screener qr code",
  "screener quarterly results",
  "screener query to find multibagger stocks",
  "screener query list",
  "screener query search",
  "screener query to find best stocks",
  "quick phonics screener",
  "qr screener",
  "quality power screener",
  "qullamaggie screener",
  "quantum screener",
  "quant screener",
  "quess corp screener",
  "quick phonics screener pdf",
  "quantify crypto screener",
  "quarterly results screener",
  "screener rental",
  "screener rental near me",
  "screener rock",
  "screener rs3",
  "screener results",
  "screener reliance",
  "screener reliance industries",
  "screener results today",
  "screener rajesh exports",
  "screener revenue",
  "reliance screener",
  "rajesh exports screener",
  "rapid mood screener",
  "rvnl screener",
  "rec screener",
  "rs3 auto screener",
  "rock screener",
  "redington screener",
  "rrp semiconductor share price screener",
  "rvnl share price screener",
  "screener stock",
  "screener screens",
  "screener survey",
  "screener stock india",
  "screener synonyms",
  "screener stock market",
  "screener shaker",
  "screener share",
  "screener survey examples",
  "screener security jobs",
  "stock screener free",
  "stock screener tradingview",
  "suzlon screener",
  "soil screener",
  "sbi screener",
  "scanx screener",
  "spot vision screener",
  "sagility screener",
  "screener tradingview",
  "screener test",
  "screener tape",
  "screener tailings",
  "screener teeth reviews",
  "screener today",
  "screener tcs",
  "screener top gainers",
  "screener tata motors",
  "screener trading",
  "tata motors screener",
  "trent screener",
  "topsoil screener",
  "tata power screener",
  "tickertape mutual fund screener",
  "tata elxsi screener",
  "titan screener",
  "screener usa",
  "screener url cinema",
  "screener undervalued stocks",
  "screener upcoming results",
  "screener upload excel",
  "screener ujjivan small finance bank",
  "screener us stocks free",
  "screener united spirits",
  "screener urban company",
  "us stock screener",
  "urban company screener",
  "utkarsh small finance bank screener",
  "undervalued stocks screener",
  "united spirits screener",
  "ujjivan small finance bank screener",
  "union bank screener",
  "uno minda screener",
  "uco bank screener",
  "upl screener",
  "screener vhs",
  "screener vs diagnostic assessment",
  "screener vhs tapes",
  "screener vs scanner",
  "screener vs assessment",
  "screener vs cam",
  "screener version",
  "screener version of c-ssrs",
  "screener vhs meaning",
  "screener vedanta",
  "vedanta screener",
  "vikram solar screener",
  "vbl screener",
  "varun beverages screener",
  "vishal mega mart screener",
  "voltas screener",
  "vaibhav global screener",
  "vikran engineering screener",
  "vbl share price screener",
  "vodafone idea screener",
  "screener website",
  "screener watch party",
  "screener watch movies together",
  "screener watch movies",
  "screener wipro",
  "screener waaree energies",
  "screener website for stocks",
  "screener web",
  "screener wockhardt",
  "screener waaree renewable technologies",
  "wipro screener",
  "waaree energies screener",
  "www screener com login",
  "www screener in app",
  "www chartink com screener",
  "www screener com india",
  "www stock screener in",
  "what is dex screener",
  "www intraday screener com",
  "who adhd screener",
  "screener xauusd",
  "screener x dhan",
  "screener xchanging solutions",
  "screener x ray",
  "screener xpro india",
  "screener xpro",
  "xrp screener",
  "xelpmoc screener",
  "x ray screener jobs",
  "xauusd screener",
  "xpro india screener",
  "xchanging solutions screener",
  "x ray screener",
  "xrp dex screener",
  "xpro screener",
  "xtranet technologies screener",
  "x1 ninja screener",
  "x ray screener jobs in india",
  "screener yahoo finance",
  "screener yes bank",
  "screener yatharth hospital",
  "screener yasho industries",
  "screener youtube",
  "screener yatra",
  "screener yatharth",
  "screener yearly subscription",
  "screener yes bank share price",
  "what is a screener test",
  "yahoo finance screener",
  "yahoo stock screener",
  "yes bank screener",
  "yahoo finance stock screener",
  "yahoo screener",
  "yale brown ocd screener",
  "yatharth hospital screener",
  "yatharth screener",
  "yes bank share screener",
  "yes bank share price screener",
  "screener zerodha",
  "screener zomato",
  "screener zen technologies",
  "screener zaggle",
  "screener zee entertainment",
  "screener zeel",
  "screener zydus life",
  "screener zydus wellness",
  "screener zaggle prepaid",
  "screener zentech",
  "zomato screener",
  "zacks stock screener",
  "zaggle screener",
  "zerodha screener",
  "zen technologies screener",
  "zomato share price screener",
  "zydus lifesciences screener",
  "zydus wellness screener",
  "zen technologies share price screener",
  "zydus screener",
  "0dte screener",
  "klse screener 0116",
  "fib 0.618 screener",
  "screener trackid sp 006",
  "vineland screener 0 6",
  "vineland screener 0 12",
  "scanner vs screener",
  "spot vision screener results",
  "0169 kl screener",
  "0 point cognitive screener",
  "auto screener v1 080",
  "tradingview stock screener v2.0",
  "coinage crypto screener v3 0",
  "screener 1000 stocks",
  "screener 100",
  "screener 15 min breakout",
  "screener 100x multibagger stocks",
  "screener 100 stocks",
  "screener 1000",
  "screener midcap 150",
  "screener nifty 100",
  "100 percent accuracy screener chartink",
  "10 point cognitive screener",
  "10 point cognitive screener 10 cs",
  "10 minute geriatric screener",
  "1 minute volume spike screener",
  "100 delivery stocks screener",
  "100 crore company com login screener",
  "15 min consolidation stocks screener",
  "10 point cognitive screener pdf",
  "10x compounding screener",
  "screener 2.0",
  "screener 20 microns",
  "screener 200 dma",
  "screener 2.0 tradingview",
  "screener 200 ema",
  "screener 2026",
  "screener 20 ema",
  "200 ema screener chartink",
  "20 microns screener",
  "20 ema screener",
  "200 ema screener",
  "200 dma screener",
  "200 ema breakout stocks screener",
  "2 question food insecurity screener",
  "20 microns share price screener",
  "200 ema stock screener",
  "20 microns share screener",
  "screener 3m india",
  "screener 360",
  "screener 360 one",
  "screener 360 one wam",
  "screener 3i infotech",
  "screener 3d model",
  "screener 3m",
  "screener 3d",
  "screener 3b blackbio",
  "360 one screener",
  "360 one wam screener",
  "3m india screener",
  "3i infotech screener",
  "3m india share price screener",
  "3 way screener",
  "360 one share price screener",
  "3 way screener for sale",
  "3m screener",
  "3b blackbio screener",
  "screener 44 moving average",
  "4k screener",
  "45 day screener",
  "44 moving average screener",
  "45 degree angle stock screener",
  "44 ma screener",
  "44 ma stock screener",
  "4th grade math screener",
  "4 year old language screener",
  "44 sma rising stocks screener",
  "44 sma screener",
  "screener 52 week low",
  "screener 52 week high",
  "screener 52 week low stocks",
  "screener 52 week high stocks",
  "screener 50 down stocks",
  "screener 500",
  "screener 50",
  "screener 5paisa",
  "screener 50 dma",
  "52 week low stocks screener",
  "52 week high stocks screener",
  "52 week low screener",
  "5paisa screener",
  "52 week high screener",
  "5paisa stock screener",
  "52 week high stocks screener chartink",
  "5 minute volume spike screener",
  "52 week high breakout stocks screener",
  "52 week low etf screener",
  "screener 63 moons",
  "683 screener",
  "693 screener",
  "63 moons screener",
  "6 item screener",
  "63 moons share price screener",
  "6 month low stocks screener",
  "6 item screener dementia",
  "63 moons technologies screener",
  "621 mccloskey screener",
  "63 moons share screener",
  "6th grade language screener",
  "7nr screener",
  "7th grade dyslexia screener texas",
  "7nr retail share price screener",
  "72 wolverine dirt screener",
  "7th grade language screener",
  "7nr retail screener",
  "gad 7 screener",
  "nr 7 screener",
  "rsi above 70 screener",
  "screener 8n",
  "883 screener",
  "883 screener for sale",
  "autism screener 8 year old",
  "finlay 883 screener",
  "colt 800 screener",
  "finlay 863 screener",
  "exit 8 screener",
  "kleemann 802 screener",
  "811 locate ticker screener",
  "8 21 ema crossover screener",
  "811 ticket screener",
  "terex 883 screener",
  "rsi above 80 screener",
  "95 screener",
  "klse screener 99 speedmart",
  "phq 9 screener",
  "one 97 screener",
  "is screener free",
  "what is screener quality",
  "9 21 ema crossover screener",
  "95 phonics screener",
  "95 phonics screener for intervention pdf",
  "95 phonics screener for intervention",
  "99 speedmart klse screener",
  "9 ema screener",
  "95 phonics screener for intervention psi",
  "99smart klse screener",
  "95 group phonics screener",
  "screener stocks",
];

export const stocksKeywords: string[] = [
  "stock market",
  "what is the stock market",
  "how does the stock market work",
  "stock market for beginners",
  "how to invest in stocks for beginners",
  "stock market basics",
  "stock market today",
  "stock market news today",
  "stock market live updates",
  "stock market hours",
  "stock market crash",
  "stock market correction meaning",
  "what is a stock market index",
  "global stock markets today",
  "Asian stock markets today",
  "how to read a stock ticker",
  "stock market volatility explained",
  "what is a circuit breaker in the stock market",
  "stock market terms glossary",
  "stock market timing in USA",
  "best stock trading platforms",
  "best stock market simulator",
  "best long term stocks to hold",
  "blue chip stocks meaning",
  "penny stocks meaning",
  "multibagger stocks meaning",
  "stocks and shares ISA explained",
  "stock analysis",
  "how to analyze a stock before buying",
  "how to read stock charts",
  "stock chart patterns cheat sheet",
  "volume analysis in stock trading",
  "growth stock vs value stock",
  "peer comparison stock analysis",
  "sector analysis in the stock market",
  "how interest rates affect the stock market",
  "how inflation affects the stock market",
  "stock fundamentals explained",
  "what is EPS in the stock market",
  "stock ratio analysis cheat sheet",
  "SpaceX stock price",
  "latest stock market news",
  "breaking stock news",
  "most active stocks today",
  "stock market news USA today",
  "stock market outlook today",
  "stocks to watch today",
  "screen stocks by P/E ratio",
  "screen stocks by market cap",
  "best stock analysis app",
  "AI stock analysis tool",
  "free stock analysis website",
  "stock comparison tool",
  "compare two stocks side by side",
  "best websites for stock research",
  "how to invest in stocks step by step",
  "real estate vs stocks investing",
  "how to file taxes for stock trading",
  "why is a stock down today",
  "why is a stock up today",
  "is the stock market going to crash",
  "how many stocks should I own",
  "stocks vs bonds",
  "what moves stock prices",
  "why did the stock market drop today",
  "best defensive stocks during a recession",
  "what to do when the stock market crashes",
  "how risky is the stock market",
  "Saudi stock exchange Tadawul",
  "Nigerian Stock Exchange top stocks",
  "Pakistan Stock Exchange PSX",
  "Dhaka Stock Exchange Bangladesh",
  "Philippine Stock Exchange PSE",
  "Hong Kong Stock Exchange HKEX",
  "Nvidia stock analysis",
  "Palantir stock forecast",
  "Micron stock analysis",
  "quantum computing stocks to watch",
  "AI stocks to buy 2026",
  "semiconductor stocks to watch",
  "Magnificent Seven stocks explained",
  "clean energy stocks to watch",
  "space stocks to invest in",
  "robotics stocks to watch",
  "cybersecurity stocks to buy",
  "data center stocks to watch",
  "NVIDIA stock price",
  "NVIDIA share price today",
  "NVIDIA stock forecast",
  "Is NVIDIA stock a good buy",
  "NVDA stock chart",
  "Apple stock price",
  "Apple share price today",
  "Apple stock forecast",
  "Is Apple stock a good buy",
  "AAPL stock chart",
  "Alphabet (Google) stock price",
  "Alphabet (Google) share price today",
  "Alphabet (Google) stock forecast",
  "Is Alphabet (Google) stock a good buy",
  "GOOGL stock chart",
  "Microsoft stock price",
  "Microsoft share price today",
  "Microsoft stock forecast",
  "Is Microsoft stock a good buy",
  "MSFT stock chart",
  "Amazon stock price",
  "Amazon share price today",
  "Amazon stock forecast",
  "Is Amazon stock a good buy",
  "AMZN stock chart",
  "Meta Platforms stock price",
  "Meta Platforms share price today",
  "Meta Platforms stock forecast",
  "Is Meta Platforms stock a good buy",
  "META stock chart",
  "Tesla stock price",
  "Tesla share price today",
  "Tesla stock forecast",
  "Is Tesla stock a good buy",
  "TSLA stock chart",
  "Broadcom stock price",
  "Broadcom share price today",
  "Broadcom stock forecast",
  "Is Broadcom stock a good buy",
  "AVGO stock chart",
  "Berkshire Hathaway stock price",
  "Berkshire Hathaway share price today",
  "Berkshire Hathaway stock forecast",
  "Is Berkshire Hathaway stock a good buy",
  "BRK.B stock chart",
  "Eli Lilly stock price",
  "Eli Lilly share price today",
  "Eli Lilly stock forecast",
  "Is Eli Lilly stock a good buy",
  "LLY stock chart",
  "SpaceX share price today",
  "SpaceX stock forecast",
  "Is SpaceX stock a good buy",
  "SPCX stock chart",
  "JPMorgan Chase stock price",
  "JPMorgan Chase share price today",
  "JPMorgan Chase stock forecast",
  "Is JPMorgan Chase stock a good buy",
  "JPM stock chart",
  "Visa stock price",
  "Visa share price today",
  "Visa stock forecast",
  "Is Visa stock a good buy",
  "V stock chart",
  "Walmart stock price",
  "Walmart share price today",
  "Walmart stock forecast",
  "Is Walmart stock a good buy",
  "WMT stock chart",
  "Mastercard stock price",
  "Mastercard share price today",
  "Mastercard stock forecast",
  "Is Mastercard stock a good buy",
  "MA stock chart",
  "Netflix stock price",
  "Netflix share price today",
  "Netflix stock forecast",
  "Is Netflix stock a good buy",
  "NFLX stock chart",
  "ExxonMobil stock price",
  "ExxonMobil share price today",
  "ExxonMobil stock forecast",
  "Is ExxonMobil stock a good buy",
  "XOM stock chart",
  "Palantir Technologies stock price",
  "Palantir Technologies share price today",
  "Palantir Technologies stock forecast",
  "Is Palantir Technologies stock a good buy",
  "PLTR stock chart",
  "Micron Technology stock price",
  "Micron Technology share price today",
  "Micron Technology stock forecast",
  "Is Micron Technology stock a good buy",
  "MU stock chart",
  "AMD stock price",
  "AMD share price today",
  "AMD stock forecast",
  "Is AMD stock a good buy",
  "AMD stock chart",
  "Costco stock price",
  "Costco share price today",
  "Costco stock forecast",
  "Is Costco stock a good buy",
  "COST stock chart",
  "Oracle stock price",
  "Oracle share price today",
  "Oracle stock forecast",
  "Is Oracle stock a good buy",
  "ORCL stock chart",
  "Coca-Cola stock price",
  "Coca-Cola share price today",
  "Coca-Cola stock forecast",
  "Is Coca-Cola stock a good buy",
  "KO stock chart",
  "Salesforce stock price",
  "Salesforce share price today",
  "Salesforce stock forecast",
  "Is Salesforce stock a good buy",
  "CRM stock chart",
  "Reliance Industries stock price",
  "Reliance Industries share price today",
  "Reliance Industries stock forecast",
  "Is Reliance Industries stock a good buy",
  "RELIANCE stock chart",
  "HDFC Bank stock price",
  "HDFC Bank share price today",
  "HDFC Bank stock forecast",
  "Is HDFC Bank stock a good buy",
  "HDFCBANK stock chart",
  "Bharti Airtel stock price",
  "Bharti Airtel share price today",
  "Bharti Airtel stock forecast",
  "Is Bharti Airtel stock a good buy",
  "BHARTIARTL stock chart",
  "TCS stock price",
  "TCS share price today",
  "TCS stock forecast",
  "Is TCS stock a good buy",
  "TCS stock chart",
  "SBIN stock chart",
  "ICICI Bank stock price",
  "ICICI Bank share price today",
  "ICICI Bank stock forecast",
  "Is ICICI Bank stock a good buy",
  "ICICIBANK stock chart",
  "Bajaj Finance stock price",
  "Bajaj Finance share price today",
  "Bajaj Finance stock forecast",
  "Is Bajaj Finance stock a good buy",
  "BAJFINANCE stock chart",
  "Hindustan Unilever stock price",
  "Hindustan Unilever share price today",
  "Hindustan Unilever stock forecast",
  "Is Hindustan Unilever stock a good buy",
  "HINDUNILVR stock chart",
  "Larsen & Toubro stock price",
  "Larsen & Toubro share price today",
  "Larsen & Toubro stock forecast",
  "Is Larsen & Toubro stock a good buy",
  "LT stock chart",
  "Life Insurance Corporation stock price",
  "Life Insurance Corporation share price today",
  "Life Insurance Corporation stock forecast",
  "Is Life Insurance Corporation stock a good buy",
  "LICI stock chart",
  "Infosys stock price",
  "Infosys share price today",
  "Infosys stock forecast",
  "Is Infosys stock a good buy",
  "INFY stock chart",
  "Kotak Mahindra Bank stock price",
  "Kotak Mahindra Bank share price today",
  "Kotak Mahindra Bank stock forecast",
  "Is Kotak Mahindra Bank stock a good buy",
  "KOTAKBANK stock chart",
  "HCL Technologies stock price",
  "HCL Technologies share price today",
  "HCL Technologies stock forecast",
  "Is HCL Technologies stock a good buy",
  "HCLTECH stock chart",
  "Maruti Suzuki stock price",
  "Maruti Suzuki share price today",
  "Maruti Suzuki stock forecast",
  "Is Maruti Suzuki stock a good buy",
  "MARUTI stock chart",
  "Sun Pharma stock price",
  "Sun Pharma share price today",
  "Sun Pharma stock forecast",
  "Is Sun Pharma stock a good buy",
  "SUNPHARMA stock chart",
  "Adani Enterprises stock price",
  "Adani Enterprises share price today",
  "Adani Enterprises stock forecast",
  "Is Adani Enterprises stock a good buy",
  "ADANIENT stock chart",
  "Titan Company stock price",
  "Titan Company share price today",
  "Titan Company stock forecast",
  "Is Titan Company stock a good buy",
  "TITAN stock chart",
  "Axis Bank stock price",
  "Axis Bank share price today",
  "Axis Bank stock forecast",
  "Is Axis Bank stock a good buy",
  "AXISBANK stock chart",
  "NTPC stock price",
  "NTPC share price today",
  "NTPC stock forecast",
  "Is NTPC stock a good buy",
  "NTPC stock chart",
  "Tata Motors stock price",
  "Tata Motors share price today",
  "Tata Motors stock forecast",
  "Is Tata Motors stock a good buy",
  "TATAMOTORS stock chart",
  "Wipro stock price",
  "Wipro share price today",
  "Wipro stock forecast",
  "Is Wipro stock a good buy",
  "WIPRO stock chart",
  "Asian Paints stock price",
  "Asian Paints share price today",
  "Asian Paints stock forecast",
  "Is Asian Paints stock a good buy",
  "ASIANPAINT stock chart",
  "AstraZeneca stock price",
  "AstraZeneca share price today",
  "AstraZeneca stock forecast",
  "Is AstraZeneca stock a good buy",
  "AZN stock chart",
  "Shell stock price",
  "Shell share price today",
  "Shell stock forecast",
  "Is Shell stock a good buy",
  "SHEL stock chart",
  "HSBA stock chart",
  "Unilever stock price",
  "Unilever share price today",
  "Unilever stock forecast",
  "Is Unilever stock a good buy",
  "ULVR stock chart",
  "Rio Tinto stock price",
  "Rio Tinto share price today",
  "Rio Tinto stock forecast",
  "Is Rio Tinto stock a good buy",
  "RIO stock chart",
  "BP stock price",
  "BP share price today",
  "BP stock forecast",
  "Is BP stock a good buy",
  "BP stock chart",
  "GSK stock price",
  "GSK share price today",
  "GSK stock forecast",
  "Is GSK stock a good buy",
  "GSK stock chart",
  "Diageo stock price",
  "Diageo share price today",
  "Diageo stock forecast",
  "Is Diageo stock a good buy",
  "DGE stock chart",
  "BATS stock chart",
  "RR stock chart",
  "BAE Systems stock price",
  "BAE Systems share price today",
  "BAE Systems stock forecast",
  "Is BAE Systems stock a good buy",
  "BA stock chart",
  "Lloyds Banking Group stock price",
  "Lloyds Banking Group share price today",
  "Lloyds Banking Group stock forecast",
  "Is Lloyds Banking Group stock a good buy",
  "LLOY stock chart",
  "Barclays stock price",
  "Barclays share price today",
  "Barclays stock forecast",
  "Is Barclays stock a good buy",
  "BARC stock chart",
  "Vodafone Group stock price",
  "Vodafone Group share price today",
  "Vodafone Group stock forecast",
  "Is Vodafone Group stock a good buy",
  "VOD stock chart",
  "Tesco stock price",
  "Tesco share price today",
  "Tesco stock forecast",
  "Is Tesco stock a good buy",
  "TSCO stock chart",
  "Shopify stock price",
  "Shopify share price today",
  "Shopify stock forecast",
  "Is Shopify stock a good buy",
  "SHOP stock chart",
  "Royal Bank of Canada stock price",
  "Royal Bank of Canada share price today",
  "Royal Bank of Canada stock forecast",
  "Is Royal Bank of Canada stock a good buy",
  "RY stock chart",
  "Toronto-Dominion Bank stock price",
  "Toronto-Dominion Bank share price today",
  "Toronto-Dominion Bank stock forecast",
  "Is Toronto-Dominion Bank stock a good buy",
  "TD stock chart",
  "Canadian National Railway stock price",
  "Canadian National Railway share price today",
  "Canadian National Railway stock forecast",
  "Is Canadian National Railway stock a good buy",
  "CNR stock chart",
  "Enbridge stock price",
  "Enbridge share price today",
  "Enbridge stock forecast",
  "Is Enbridge stock a good buy",
  "ENB stock chart",
  "Brookfield Corporation stock price",
  "Brookfield Corporation share price today",
  "Brookfield Corporation stock forecast",
  "Is Brookfield Corporation stock a good buy",
  "BN stock chart",
  "Bank of Montreal stock price",
  "Bank of Montreal share price today",
  "Bank of Montreal stock forecast",
  "Is Bank of Montreal stock a good buy",
  "BMO stock chart",
  "Canadian Pacific Kansas City stock price",
  "Canadian Pacific Kansas City share price today",
  "Canadian Pacific Kansas City stock forecast",
  "Is Canadian Pacific Kansas City stock a good buy",
  "CP stock chart",
  "Barrick Gold stock price",
  "Barrick Gold share price today",
  "Barrick Gold stock forecast",
  "Is Barrick Gold stock a good buy",
  "ABX stock chart",
  "Suncor Energy stock price",
  "Suncor Energy share price today",
  "Suncor Energy stock forecast",
  "Is Suncor Energy stock a good buy",
  "SU stock chart",
  "Manulife Financial stock price",
  "Manulife Financial share price today",
  "Manulife Financial stock forecast",
  "Is Manulife Financial stock a good buy",
  "MFC stock chart",
  "Bank of Nova Scotia stock price",
  "Bank of Nova Scotia share price today",
  "Bank of Nova Scotia stock forecast",
  "Is Bank of Nova Scotia stock a good buy",
  "BNS stock chart",
  "BHP Group stock price",
  "BHP Group share price today",
  "BHP Group stock forecast",
  "Is BHP Group stock a good buy",
  "BHP stock chart",
  "Commonwealth Bank of Australia stock price",
  "Commonwealth Bank of Australia share price today",
  "Commonwealth Bank of Australia stock forecast",
  "Is Commonwealth Bank of Australia stock a good buy",
  "CBA stock chart",
  "CSL Limited stock price",
  "CSL Limited share price today",
  "CSL Limited stock forecast",
  "Is CSL Limited stock a good buy",
  "CSL stock chart",
  "National Australia Bank stock price",
  "National Australia Bank share price today",
  "National Australia Bank stock forecast",
  "Is National Australia Bank stock a good buy",
  "NAB stock chart",
  "Westpac Banking stock price",
  "Westpac Banking share price today",
  "Westpac Banking stock forecast",
  "Is Westpac Banking stock a good buy",
  "WBC stock chart",
  "ANZ Group stock price",
  "ANZ Group share price today",
  "ANZ Group stock forecast",
  "Is ANZ Group stock a good buy",
  "ANZ stock chart",
  "Macquarie Group stock price",
  "Macquarie Group share price today",
  "Macquarie Group stock forecast",
  "Is Macquarie Group stock a good buy",
  "MQG stock chart",
  "Wesfarmers stock price",
  "Wesfarmers share price today",
  "Wesfarmers stock forecast",
  "Is Wesfarmers stock a good buy",
  "WES stock chart",
  "Woodside Energy stock price",
  "Woodside Energy share price today",
  "Woodside Energy stock forecast",
  "Is Woodside Energy stock a good buy",
  "WDS stock chart",
  "Telstra Group stock price",
  "Telstra Group share price today",
  "Telstra Group stock forecast",
  "Is Telstra Group stock a good buy",
  "TLS stock chart",
  "Fortescue stock price",
  "Fortescue share price today",
  "Fortescue stock forecast",
  "Is Fortescue stock a good buy",
  "FMG stock chart",
  "Woolworths Group stock price",
  "Woolworths Group share price today",
  "Woolworths Group stock forecast",
  "Is Woolworths Group stock a good buy",
  "WOW stock chart",
  "Toronto Stock Exchange (TSX)",
  "Hong Kong Stock Exchange (HKEX)",
  "Tokyo Stock Exchange (TSE)",
  "Johannesburg Stock Exchange (JSE)",
  "Pakistan Stock Exchange (PSX)",
  "Dhaka Stock Exchange (DSE)",
  "Philippine Stock Exchange (PSE)",
  "Shanghai Stock Exchange",
  "Shenzhen Stock Exchange",
  "Robinhood stock trading",
  "stocks and shares ISA",
  "German stocks to buy",
  "stocks and bonds",
  "stocks app",
  "stocks apple",
  "stocks at 52 week lows",
  "stocks and bonds omaha",
  "stocks after hours",
  "stocks and blondes",
  "stocks are down",
  "stocks at 52 week lows today",
  "stocks and blondes chicago",
  "ai stocks to buy",
  "are stocks down today",
  "stocks by market cap",
  "stocks bakery menu",
  "stocks biggest losers today",
  "stocks bakery philadelphia",
  "stocks biggest gainers today",
  "stocks below 200 day moving average",
  "stocks biggest losers",
  "stocks basketball",
  "best stocks to invest in right now",
  "best stocks to invest in",
  "best penny stocks to buy now",
  "best penny stocks to buy",
  "best stocks and shares isa uk",
  "best stocks to invest in 2026",
  "stocks crash",
  "stocks chart",
  "stocks calculator",
  "stocks cnbc",
  "stocks closed today",
  "stocks crashing today",
  "stocks cnn",
  "stocks coffee",
  "stocks cold brew",
  "cheap stocks to buy now",
  "common stocks and uncommon profits",
  "stocks down today",
  "stocks down",
  "stocks definition",
  "stocks dropping today",
  "stocks down today why",
  "stocks dropping",
  "stocks down the most today",
  "stocks down the most this year",
  "stocks dow",
  "stocks expected to rise this week",
  "stocks en espa\u00f1ol",
  "stocks expected to rise in 2026",
  "stocks expected to split in 2026",
  "stocks expected to rise tomorrow",
  "stocks explained",
  "stocks expected to rise",
  "stocks emoji",
  "energy stocks to buy",
  "stocks for beginners",
  "stocks for dummies",
  "stocks fall",
  "stocks falling today",
  "stocks for kids to invest in",
  "stocks for the long run",
  "f&o stocks list",
  "stocks google",
  "stocks going down",
  "stocks graph",
  "stocks going up",
  "stocks game",
  "stocks going up today",
  "stocks going down today",
  "stocks gta 5",
  "stocks going public soon",
  "good stocks to invest in",
  "good stocks to buy right now",
  "stocks heat map",
  "stocks have which of the following characteristics",
  "stocks hitting 52 week lows",
  "stocks halted today",
  "stocks how to invest",
  "stocks hitting 52 week low today",
  "stocks halted",
  "stocks hours",
  "stocks how do they work",
  "how are stocks today",
  "stocks in spanish",
  "stocks in the dow",
  "stocks investment",
  "stocks in qqq",
  "stocks i should invest in right now",
  "it stocks news",
  "it stocks today",
  "it stocks down today",
  "it stocks to buy",
  "it stocks us",
  "stocks jobs",
  "stocks jail",
  "stocks just flashed a rare market signal",
  "stocks jumping today",
  "stocks july 2026",
  "stocks jnj",
  "stocks japan",
  "stocks july 3",
  "junior stocks and shares isa",
  "junior stocks and shares isa uk",
  "stocks kids would be interested in",
  "stocks keep going down",
  "stocks ko",
  "stocks korea",
  "stocks kalshi",
  "stocks keep going up",
  "stocks kia",
  "stocks keep falling",
  "stocks ktos",
  "stocks keyboard",
  "kids stocks and shares isa",
  "stocks live",
  "stocks likely to split in 2026",
  "stocks list",
  "stocks long term capital gains tax",
  "stocks like sandisk",
  "stocks like micron",
  "stocks like voo",
  "stocks live today",
  "stocks like nvidia",
  "stocks live chart",
  "stocks market",
  "stocks market today",
  "stocks meaning",
  "stocks making the biggest moves today",
  "stocks meme",
  "stocks moving today",
  "stocks making the biggest moves premarket",
  "stocks making the biggest moves after hours",
  "stocks medieval",
  "stocks moving after hours",
  "stocks news",
  "stocks news today",
  "stocks near 52 week low",
  "stocks now",
  "stocks nvda",
  "stocks nvidia",
  "stocks n bonds omaha",
  "stocks near 52 week low today",
  "stocks next week",
  "stocks near 200 day moving average",
  "stocks on the rise",
  "stocks online",
  "stocks on cash app",
  "stocks open today",
  "stocks on the rise today",
  "stocks or bonds",
  "stocks on the move today",
  "stocks on the move",
  "stocks overnight",
  "oil stocks to buy",
  "oil stocks today",
  "stocks pound cake",
  "stocks premarket",
  "stocks punishment",
  "stocks pound cake where to buy",
  "stocks prices",
  "stocks predicted to rise this week",
  "stocks predicted to rise",
  "stocks pound cake recipe",
  "stocks projected to rise in 2026",
  "penny stocks to buy",
  "penny stocks to buy now",
  "penny stocks list",
  "penny stocks to buy today",
  "penny stocks reddit",
  "stocks qqq",
  "stocks quotes",
  "stocks qqqm",
  "stocks quantum computing",
  "stocks qualcomm",
  "stocks qcom",
  "stocks quarterly results",
  "stocks quests wow classic",
  "stocks qbts",
  "stocks que es",
  "quantum computing stocks price",
  "quantum stocks to buy",
  "quantum computing stocks to buy",
  "qualcomm stocks price",
  "quantum computing stocks list",
  "stocks reddit",
  "stocks right now",
  "stocks related to spacex",
  "stocks rising today",
  "stocks rise",
  "stocks related to ai data centers",
  "stocks rn",
  "stocks spacex",
  "stocks simulator",
  "stocks shoes",
  "stocks spcx",
  "stocks splitting soon",
  "stocks set to split in 2026",
  "stocks short term capital gains tax",
  "stocks set to explode",
  "stocks splitting in 2026",
  "stocks today",
  "stocks to invest in right now",
  "stocks to buy now",
  "stocks to buy today",
  "stocks to buy",
  "stocks to invest in",
  "stocks that will explode in 2026",
  "stocks to watch",
  "the best stocks to invest in right now",
  "today stocks to watch",
  "stocks under $5 that will explode",
  "stocks under $1 that will explode",
  "stocks up today",
  "stocks under $10 that will explode",
  "stocks under 10 dollars to buy now",
  "stocks under $1",
  "stocks under $10 with high potential",
  "stocks under 10 dollars",
  "stocks under 20 dollars",
  "stocks under $20 with high potential",
  "undervalued stocks right now",
  "stocks vs bonds vs mutual funds",
  "stocks vs etfs vs mutual funds",
  "stocks vs etfs",
  "stocks vs shares",
  "stocks vs bonds vs mutual funds vs etf",
  "stocks vs mutual funds",
  "stocks voo",
  "stocks vs real estate",
  "vanguard stocks and shares isa",
  "stocks with josh",
  "stocks with a strong buy rating",
  "stocks with the highest short interest",
  "stocks worth investing in right now",
  "which stocks to buy now",
  "what stocks to invest in",
  "what ai stocks to buy",
  "stocks xrp",
  "stocks xst",
  "stocks xom",
  "stocks xle",
  "stocks yesterday",
  "stocks yahoo",
  "stocks yahoo finance",
  "stocks you should buy now",
  "stocks youtube",
  "stocks you should invest in now",
  "stocks yards",
  "stocks ytd",
  "yahoo finance stocks list",
  "yahoo stocks symbols",
  "stocks zeta",
  "stocks zts",
  "stocks zerodha",
  "stocks zscaler",
  "stocks zakat calculator",
  "stocks zoetis",
  "stocks zillow",
  "stocks zakat",
  "stocks zoom",
  "stocks zara",
  "stocks 0dte",
  "stock 0",
  "stock 0050",
  "stock 0005 price",
  "stock 0700",
  "stock 0939",
  "stock 0388",
  "stock 0981",
  "stock 001",
  "stock 0001",
  "0.05 penny stocks list",
  "stocks 101",
  "stocks 101 for beginners",
  "stocks 101 for dummies",
  "stocks 100",
  "stocks 10x",
  "stocks 101 reddit",
  "stocks 10x reddit",
  "stocks 1 dollar",
  "stocks 101 pdf",
  "13 penny stocks plunge fy26",
  "10 best stocks to buy now",
  "13 penny stocks recent decline",
  "12 penny stocks doubled wealth",
  "10 stocks to buy now",
  "10 best stocks motley fool",
  "stocks 2026",
  "stocks 2026 reddit",
  "stocks 24 hour market",
  "stocks 24/7",
  "stocks 2027",
  "stocks 2 trade",
  "stocks 2022",
  "stocks 200 day moving average",
  "stocks 2008",
  "stocks 250",
  "stocks 3 day rule",
  "stocks 30 day rule",
  "stocks 3 black crows",
  "stocks 30 down from 52 week high",
  "stocks 3.0 torn",
  "stocks 360",
  "stocks 30 down from all time high",
  "stocks 3 months low",
  "stocks 30 percent down",
  "3 tsx stocks under $30",
  "stocks 401k",
  "stocks 4 rule",
  "stocks 40 percent down",
  "stocks 40 down from 52 week high",
  "stocks 4 year cycle",
  "stocks 40 rule",
  "stock 4dx",
  "stock 4gld",
  "stocks at 44 moving average rising",
  "4 it stocks 24 upside",
  "4 stocks set to skyrocket from america\u2019s greatest energy discovery",
  "stocks 52 week lows",
  "stocks 500",
  "stocks 52 week high",
  "stocks 500 sp",
  "stocks 52 week low today",
  "stocks 50",
  "stocks 5 year lows",
  "stocks 52 week low list",
  "stocks 500 index",
  "stocks 5 dollars and under",
  "52 week high stocks chartink",
  "52 week low stocks today",
  "52 week high stocks with high volume",
  "6 stocks to buy and hold forever",
  "stocks 70 percent down",
  "stocks 7 rule",
  "stocks 7 letters",
  "stocks 7 crossword clue",
  "7 smallcap stocks 2026 potential",
  "70 30 stocks to bonds",
  "7 stocks to buy and hold forever",
  "7 stocks to buy before spacex goes public",
  "stocks 80 down",
  "stock 84 riserva",
  "stock 8",
  "stock 80",
  "stock 84 brandy price",
  "stock 88",
  "stock 84 whiskey",
  "8x8 stocks price",
  "stocks 9 ema crossing 20 ema",
  "stocks 99 nights in the forest",
  "stocks 9 ema",
  "stock 9988",
  "stock 9988 hk",
  "stock 99",
  "stock 939",
  "stock 941",
  "stock 9618",
  "9 penny stocks surge",
  "9 midcap stocks upside potential",
  "9 ema breakout stocks chartink",
  "9 penny stocks decline",
  "9 penny stocks 2 week rally",
];

export const learnKeywords: string[] = [
  "how to buy stocks",
  "how to start trading stocks",
  "pre market trading hours",
  "after hours trading explained",
  "bull market meaning",
  "bear market meaning",
  "bull market vs bear market",
  "what is short selling",
  "how does short selling work",
  "how to open a brokerage account",
  "best trading apps for beginners",
  "paper trading for beginners",
  "how to invest money",
  "long term investing strategy",
  "short term trading strategy",
  "investing for beginners",
  "best investment apps",
  "how much money do I need to start investing",
  "index fund investing",
  "mutual funds vs stocks",
  "ETF vs index fund",
  "ETF vs mutual fund",
  "best ETFs to invest in 2026",
  "best mutual funds 2026",
  "SIP investment plan",
  "best SIP for long term",
  "compound interest calculator",
  "power of compounding in investing",
  "dollar cost averaging explained",
  "retirement investment plan",
  "NPS vs mutual funds",
  "robo advisor investing",
  "how to invest with little money",
  "investing for students",
  "investing for teenagers",
  "ESG investing meaning",
  "risk tolerance in investing",
  "how to reduce investment risk",
  "active vs passive investing",
  "growth investing vs value investing",
  "Warren Buffett investing principles",
  "how to build wealth through stocks",
  "common investment mistakes to avoid",
  "how to pick winning stocks",
  "TFSA vs RRSP for investing",
  "fundamental analysis of stocks",
  "technical analysis for beginners",
  "fundamental analysis vs technical analysis",
  "how to do fundamental analysis step by step",
  "candlestick patterns explained",
  "candlestick chart for beginners",
  "moving average trading strategy",
  "RSI indicator explained",
  "MACD indicator explained",
  "bollinger bands explained",
  "support and resistance levels explained",
  "how to find support and resistance",
  "head and shoulders pattern",
  "double top and double bottom pattern",
  "how to value a stock",
  "intrinsic value of a stock",
  "discounted cash flow model explained",
  "how to calculate intrinsic value",
  "SWOT analysis of a company example",
  "how to read an equity research report",
  "how to spot overvalued stocks",
  "how to spot undervalued stocks",
  "relative valuation methods explained",
  "management quality analysis for stocks",
  "economic moat meaning in investing",
  "how to read financial statements",
  "how to read a balance sheet",
  "how to read an income statement",
  "how to read a cash flow statement",
  "revenue vs profit vs net income",
  "gross profit vs net profit",
  "how to read a company's annual report",
  "10-K report explained",
  "10-Q report explained",
  "how to read quarterly results",
  "company fundamentals checklist for investors",
  "how to evaluate the financial health of a company",
  "free cash flow explained",
  "what is EBITDA",
  "market capitalization explained",
  "large cap mid cap small cap meaning",
  "enterprise value explained",
  "shareholding pattern explained",
  "what is P/E ratio",
  "how to calculate P/E ratio",
  "what is a good P/E ratio",
  "P/B ratio explained",
  "price to book ratio meaning",
  "debt to equity ratio explained",
  "what is a good debt to equity ratio",
  "current ratio meaning",
  "quick ratio explained",
  "return on equity ROE explained",
  "return on assets ROA explained",
  "return on capital employed ROCE",
  "PEG ratio explained",
  "operating margin explained",
  "net profit margin explained",
  "gross margin explained",
  "interest coverage ratio explained",
  "book value per share explained",
  "EV/EBITDA explained",
  "asset turnover ratio explained",
  "inventory turnover ratio explained",
  "working capital ratio explained",
  "important financial ratios for investors",
  "how to use ratios to pick stocks",
  "draft red herring prospectus explained",
  "when will OpenAI go public",
  "theta decay explained",
  "selling covered calls for income",
  "cash secured puts explained",
  "F&O trading for beginners",
  "Fed meeting schedule 2026",
  "FOMC meeting dates 2026",
  "next Fed interest rate decision",
  "CPI report release date",
  "inflation report today",
  "jobs report release date",
  "non-farm payrolls explained",
  "GDP report schedule",
  "RBI monetary policy dates 2026",
  "RBI repo rate news",
  "ECB interest rate decision",
  "Bank of England rate decision",
  "market moving events this week",
  "what is the non-farm payroll report",
  "consumer confidence index explained",
  "PMI report explained",
  "how to trade around economic events",
  "central bank meetings 2026",
  "top gainers and losers today",
  "pre-market movers today",
  "after-hours movers today",
  "global markets news today",
  "best charting software for stocks",
  "beginner's guide to investing",
  "complete guide to mutual funds",
  "complete guide to ETFs",
  "guide to retirement investing",
  "how to build wealth in your 20s",
  "how to build wealth in your 30s",
  "how to start investing after college",
  "how to teach kids about investing",
  "how to invest in gold",
  "how to invest in index funds",
  "how to invest in blue chip stocks",
  "how to invest in international stocks",
  "how to invest in foreign stocks",
  "capital gains tax on stocks",
  "long term vs short term capital gains tax",
  "how to save tax through investing",
  "investment guide for women",
  "investment guide for beginners in USA",
  "is now a good time to buy stocks",
  "when to sell a stock",
  "how do I know when to sell a stock",
  "why do companies buy back stock",
  "what is insider trading",
  "is insider trading illegal",
  "what is a hedge fund",
  "what is a mutual fund",
  "what is an index fund",
  "what is a bond investment",
  "recession proof stocks",
  "how to start investing with $100",
  "can I lose all my money in stocks",
  "best discount brokers in USA",
  "best discount brokers in Canada",
  "best trading platforms UK",
  "best trading apps Australia",
  "Zerodha vs Groww comparison",
  "CDSL vs NSDL explained",
  "how to invest in the ASX",
  "how to invest in the TSX",
  "Robinhood vs eToro comparison",
  "best trading apps in UAE",
  "best brokers in Singapore",
  "Bursa Malaysia top stocks",
  "Dubai Financial Market stocks",
  "JSE South Africa top stocks",
  "Singapore Exchange SGX",
  "how to invest in Chinese stocks",
  "how to invest in Japanese stocks",
  "Nikkei 225 companies list",
  "DAX companies list Germany",
  "CAC 40 companies France",
  "how to invest in European stocks",
  "Generated Keyword",
  "NVIDIA quarterly results",
  "Apple quarterly results",
  "Alphabet (Google) quarterly results",
  "Microsoft quarterly results",
  "Amazon quarterly results",
  "Meta Platforms quarterly results",
  "Tesla quarterly results",
  "Broadcom quarterly results",
  "Berkshire Hathaway quarterly results",
  "Eli Lilly quarterly results",
  "SpaceX quarterly results",
  "JPMorgan Chase quarterly results",
  "Visa quarterly results",
  "Walmart quarterly results",
  "Mastercard quarterly results",
  "Netflix quarterly results",
  "ExxonMobil quarterly results",
  "Palantir Technologies quarterly results",
  "Micron Technology quarterly results",
  "AMD quarterly results",
  "Costco quarterly results",
  "Oracle quarterly results",
  "Coca-Cola quarterly results",
  "Salesforce quarterly results",
  "Reliance Industries quarterly results",
  "HDFC Bank quarterly results",
  "Bharti Airtel quarterly results",
  "TCS quarterly results",
  "ICICI Bank quarterly results",
  "Bajaj Finance quarterly results",
  "Hindustan Unilever quarterly results",
  "Larsen & Toubro quarterly results",
  "Life Insurance Corporation quarterly results",
  "Infosys quarterly results",
  "Kotak Mahindra Bank quarterly results",
  "HCL Technologies quarterly results",
  "Maruti Suzuki quarterly results",
  "Sun Pharma quarterly results",
  "Adani Enterprises quarterly results",
  "Titan Company quarterly results",
  "Axis Bank quarterly results",
  "NTPC quarterly results",
  "Tata Motors quarterly results",
  "Wipro quarterly results",
  "Asian Paints quarterly results",
  "AstraZeneca quarterly results",
  "Shell quarterly results",
  "Unilever quarterly results",
  "Rio Tinto quarterly results",
  "BP quarterly results",
  "GSK quarterly results",
  "Diageo quarterly results",
  "BAE Systems quarterly results",
  "Lloyds Banking Group quarterly results",
  "Barclays quarterly results",
  "Vodafone Group quarterly results",
  "Tesco quarterly results",
  "Shopify quarterly results",
  "Royal Bank of Canada quarterly results",
  "Toronto-Dominion Bank quarterly results",
  "Canadian National Railway quarterly results",
  "Enbridge quarterly results",
  "Brookfield Corporation quarterly results",
  "Bank of Montreal quarterly results",
  "Canadian Pacific Kansas City quarterly results",
  "Barrick Gold quarterly results",
  "Suncor Energy quarterly results",
  "Manulife Financial quarterly results",
  "Bank of Nova Scotia quarterly results",
  "BHP Group quarterly results",
  "Commonwealth Bank of Australia quarterly results",
  "CSL Limited quarterly results",
  "National Australia Bank quarterly results",
  "Westpac Banking quarterly results",
  "ANZ Group quarterly results",
  "Macquarie Group quarterly results",
  "Wesfarmers quarterly results",
  "Woodside Energy quarterly results",
  "Telstra Group quarterly results",
  "Fortescue quarterly results",
  "Woolworths Group quarterly results",
  "NVIDIA",
  "Apple",
  "Alphabet (Google)",
  "Microsoft",
  "Amazon",
  "Meta Platforms",
  "Tesla",
  "Broadcom",
  "Berkshire Hathaway",
  "Eli Lilly",
  "SpaceX",
  "JPMorgan Chase",
  "Visa",
  "Walmart",
  "Mastercard",
  "Netflix",
  "ExxonMobil",
  "Palantir Technologies",
  "Micron Technology",
  "AMD",
  "Costco",
  "Oracle",
  "Coca-Cola",
  "Salesforce",
  "Reliance Industries",
  "HDFC Bank",
  "Bharti Airtel",
  "TCS",
  "ICICI Bank",
  "Bajaj Finance",
  "Hindustan Unilever",
  "Larsen & Toubro",
  "Life Insurance Corporation",
  "NVDA",
  "AAPL",
  "GOOGL",
  "MSFT",
  "AMZN",
  "META",
  "TSLA",
  "AVGO",
  "BRK.B",
  "LLY",
  "SPCX",
  "JPM",
  "V",
  "WMT",
  "MA",
  "NFLX",
  "XOM",
  "PLTR",
  "MU",
  "COST",
  "ORCL",
  "KO",
  "CRM",
  "RELIANCE",
  "HDFCBANK",
  "BHARTIARTL",
  "SBIN",
  "ICICIBANK",
  "BAJFINANCE",
  "HINDUNILVR",
  "LT",
  "LICI",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "United Arab Emirates",
  "Singapore",
  "Hong Kong",
  "Germany",
  "France",
  "Japan",
  "South Africa",
  "Nigeria",
  "Pakistan",
  "Bangladesh",
  "Philippines",
  "Malaysia",
  "Saudi Arabia",
  "Brazil",
  "China",
  "Australian Securities Exchange (ASX)",
  "Dubai Financial Market (DFM)",
  "Abu Dhabi Securities Exchange (ADX)",
  "Singapore Exchange (SGX)",
  "Deutsche B\u00f6rse (Frankfurt)",
  "Euronext Paris",
  "Nigerian Exchange (NGX)",
  "Bursa Malaysia",
  "Saudi Exchange (Tadawul)",
  "B3 (Brasil Bolsa Balc\u00e3o)",
  "S&P/TSX Composite",
  "ASX 200",
  "DFM General Index",
  "Straits Times Index",
  "Hang Seng Index",
  "DAX",
  "CAC 40",
  "Nikkei 225",
  "TOPIX",
  "JSE Top 40",
  "NGX All-Share Index",
  "KSE-100",
  "DSEX",
  "PSEi",
  "TASI",
  "Ibovespa",
  "SSE Composite",
  "CSI 300",
  "401k investing",
  "SIP investment",
  "F&O trading",
  "SIPP investing",
  "TFSA investing",
  "RRSP investing",
  "superannuation investing",
  "SMSF",
  "DFM stocks",
  "best trading apps UAE",
  "SGX stocks",
  "CPF investing",
  "Hang Seng stocks",
  "DAX companies",
  "CAC 40 companies",
  "PEA investing",
  "Nikkei 225 stocks",
  "NISA investing",
  "JSE top stocks",
  "NGX top stocks",
  "PSX top stocks",
  "DSE top stocks",
  "PSE top stocks",
  "Tadawul top stocks",
  "B3 top stocks",
  "stocks",
  "nvidia stocks",
  "penny stocks",
  "quantum computing stocks",
  "ai stocks",
  "tesla stocks",
  "semiconductor stocks",
  "hybe stocks",
  "google stocks",
  "apple stocks",
  "oil stocks",
  "amd stocks",
  "adani stocks",
  "adobe stocks",
  "alphabet stocks",
  "ai best stocks",
  "blue chip stocks",
  "boyds stocks",
  "best ai stocks",
  "best penny stocks",
  "copper stocks",
  "costco stocks",
  "cnbc stocks",
  "crypto stocks",
  "cisco stocks",
  "chip stocks",
  "chevron stocks",
  "defence stocks",
  "data center stocks",
  "disney stocks",
  "drone stocks",
  "dwave stocks",
  "ethanol stocks",
  "energy stocks",
  "etf stocks",
  "energy sector stocks",
  "elon musk stocks",
  "ev stocks",
  "exon stocks",
  "fertilizer stocks",
  "fmcg stocks",
  "figma stocks",
  "foundation stocks",
  "ford stocks",
  "fiserv stocks",
  "f&o stocks",
  "ferrari stocks",
  "gold mining stocks",
  "green energy stocks",
  "grayboe stocks",
  "grow a garden stocks",
  "growth stocks",
  "google finance stocks",
  "graphene stocks",
  "how to invest in stocks",
  "how to buy ai stocks",
  "how much is nvidia stocks",
  "how much are apple stocks",
  "how much are tesla stocks",
  "intel stocks",
  "ibm stocks",
  "invest in stocks",
  "it penny stocks",
  "jane street stocks",
  "joint stocks",
  "japanese stocks",
  "japan stocks",
  "jewellery stocks",
  "jollibee stocks",
  "j&j stocks",
  "joby stocks",
  "kalyan jewellers stocks",
  "kroger stocks",
  "korean stocks",
  "krg stocks",
  "kyndryl stocks",
  "klarna stocks",
  "kotak research short term stocks",
  "kraken stocks",
  "korea stocks",
  "lithium stocks",
  "large cap stocks",
  "lockheed martin stocks",
  "lucid stocks",
  "lululemon stocks",
  "long term stocks",
  "live stocks",
  "long term investment stocks",
  "low pe stocks",
  "magnificent 7 stocks",
  "micron stocks",
  "meta stocks",
  "mag 7 stocks",
  "most active stocks",
  "magpul stocks",
  "mcmillan stocks",
  "meme stocks",
  "manners stocks",
  "nvda stocks",
  "nuclear energy stocks",
  "netflix stocks",
  "nuclear stocks",
  "nike stocks",
  "nancy pelosi stocks",
  "oracle stocks",
  "oil company stocks",
  "openai stocks",
  "one piece stocks",
  "oversold stocks",
  "oil and gas stocks",
  "oklo stocks",
  "pharma stocks",
  "paypal stocks",
  "price volume breakout stocks",
  "power of stocks",
  "quantum stocks",
  "qualcomm stocks",
  "qqq stocks",
  "qcom stocks",
  "reddit stocks",
  "rare earth stocks",
  "reit stocks",
  "registry of joint stocks",
  "robin hood stocks",
  "railway stocks",
  "renewable energy stocks",
  "robotics stocks",
  "real estate stocks",
  "rockstar stocks",
  "silver stocks",
  "small cap stocks",
  "stefanutti stocks",
  "space stocks",
  "spacex stocks",
  "samsung stocks",
  "strong buy stocks",
  "tech stocks",
  "today's stocks",
  "the magnificent 7 stocks",
  "the mag 7 stocks",
  "the best ai stocks",
  "to buy stocks",
  "uranium stocks",
  "undervalued stocks",
  "ubisoft stocks",
  "upper circuit stocks",
  "ups stocks",
  "up and coming stocks",
  "vedanta stocks",
  "vedanta demerger stocks",
  "value stocks",
  "voo stocks",
  "vedanta power stocks",
  "visa stocks",
  "verizon stocks",
  "volatile stocks",
  "vanguard stocks",
  "what are penny stocks",
  "what are blue chip stocks",
  "what are the mag 7 stocks",
  "what are the magnificent 7 stocks",
  "what are quantum stocks",
  "what are ai stocks",
  "what are semiconductor stocks",
  "xrp stocks",
  "xiaomi stocks",
  "xbox stocks",
  "xom stocks",
  "xpeng stocks",
  "xai stocks",
  "xero stocks",
  "xeqt stocks",
  "xerox stocks",
  "xle stocks",
  "yahoo stocks",
  "yahoo finance stocks",
  "yahoo most active stocks",
  "yahoo trending stocks",
  "youtube stocks",
  "yahoo penny stocks",
  "yahoo finance penny stocks",
  "zscaler stocks",
  "zoom stocks",
  "zacks strong buy stocks",
  "zomato stocks",
  "zacks stocks",
  "zacks rank 1 stocks",
  "zeta stocks",
  "zoho stocks",
  "0dte stocks",
  "0.01 penny stocks",
  "0 debt stocks",
  "0.01 stocks",
  "07 13 denali stocks",
  "0823 hk stocks",
  "0.0001 stocks",
  "07 13 chevy stocks",
  "10 best uranium stocks",
  "15 minute breakout stocks",
  "10 22 ruger stocks",
  "10 top stocks",
  "3m stocks",
  "35 multibagger stocks",
  "3d printing stocks",
  "30 dow stocks",
  "3 month low stocks",
  "3 day rule stocks",
  "3 types of stocks",
  "350z stocks",
  "peak 44 stocks",
  "44 moving average rising stocks",
  "401k stocks",
  "4th gen laramie stocks",
  "4th gen stocks",
  "4th gen limited stocks",
  "44 sma rising stocks",
  "44 ema rising stocks",
  "4runner stocks",
  "52 week low stocks",
  "52 week high stocks",
  "52 week high breakout stocks",
  "stoxx 600 stock",
  "6 recommended long term stocks",
  "6 month low stocks",
  "6.4 stocks",
  "6g stocks",
  "6 month breakout stocks",
  "6.4 king ranch stocks",
  "7 magnificent stocks",
  "7 rule stocks",
  "75 promoter holding penny stocks",
  "7 11 stocks",
  "7 percent rule stocks",
  "7 eleven stocks",
  "8x8 stocks",
  "870 stocks",
  "8x6 5 chevy stocks",
  "8x170 stocks",
  "8x180 stocks",
  "8x180 denali stocks",
  "80 percent down stocks",
  "90 promoter holding penny stocks",
  "9 21 ema crossover stocks",
  "9 ema breakout stocks",
  "90 promoter holding stocks",
];

export const optionsKeywords: string[] = [
  "best investment options 2026",
  "best 401k investment options",
  "superannuation investment options",
  "what is options trading",
  "options trading for beginners",
  "call option vs put option",
  "how to trade options",
  "options trading strategies for beginners",
  "covered call strategy explained",
  "protective put strategy explained",
  "options greeks explained",
  "what is delta in options trading",
  "what is theta in options trading",
  "what is gamma in options trading",
  "what is implied volatility",
  "how to read an options chain",
  "iron condor strategy explained",
  "vertical spread options strategy",
  "bull call spread explained",
  "bear put spread explained",
  "straddle vs strangle options",
  "options trading vs stock trading",
  "best options trading platforms",
  "weekly options trading strategy",
  "0DTE options explained",
  "options expiration date explained",
  "options trading for income",
  "options trading risk management",
  "how much money to start options trading",
  "paper trading options",
  "best options trading course for beginners",
  "LEAPS options explained",
  "options assignment explained",
  "in the money vs out of the money options",
  "best stocks for options trading",
  "futures and options trading explained",
  "guide to options trading for beginners",
  "best tax saving investment options",
  "options screener",
  "0dte options screener",
  "stocks futures",
  "stocks vs options",
];

export const calendarKeywords: string[] = [
  "stock market holidays 2026",
  "dividend investing strategy",
  "dividend yield explained",
  "what is a good dividend yield",
  "dividend payout ratio explained",
  "economic calendar",
  "economic calendar today",
  "economic calendar this week",
  "earnings calendar this week",
  "earnings season 2026 dates",
  "upcoming earnings reports",
  "quarterly results calendar India",
  "how the economic calendar affects the stock market",
  "stock market holiday calendar 2026",
  "dividend calendar ex-dividend dates",
  "stock screener for dividend stocks",
  "guide to dividend investing",
  "how are dividends taxed",
  "what happens when a stock splits",
  "what is a stock split",
  "why do companies do stock splits",
  "what is a reverse stock split",
  "what is a dividend",
  "how do dividends work",
  "how often are dividends paid",
  "what is a stock buyback",
  "dividend aristocrats list",
  "screener dividend stocks",
  "screener dividend",
  "dividend paying stocks",
  "stocks earnings this week",
  "stocks earnings today",
  "stocks going ex dividend this week",
  "high dividend stocks",
  "monthly dividend stocks",
  "stocks paying highest dividends",
  "stocks reporting earnings today",
  "stocks reporting earnings this week",
  "stocks reporting earnings after the bell today",
  "stocks that pay dividends",
  "the highest dividend stocks",
  "stocks with highest dividends",
  "stocks with the highest dividend yield",
  "stocks with dividends",
  "stocks with high dividends",
  "stocks with best dividends",
  "stocks with ex dividend dates this week",
  "3 dividend stocks january 2026",
  "6 dividend yield stocks",
  "6 dividend stocks",
  "6 percent dividend stocks",
  "8 dividend yield stocks",
  "8 dividend stocks",
];

export const ipoKeywords: string[] = [
  "what is an IPO",
  "how does an IPO work",
  "upcoming IPOs 2026",
  "IPO calendar 2026",
  "IPO calendar USA",
  "IPO calendar India",
  "how to apply for an IPO",
  "IPO allotment status check",
  "IPO GMP today",
  "what is grey market premium",
  "best IPOs to invest in 2026",
  "IPO listing gains explained",
  "how to invest in an IPO online",
  "SPAC vs traditional IPO",
  "IPO subscription status",
  "recently listed IPOs",
  "should I invest in an IPO",
  "IPO lock-up period explained",
  "how IPO pricing works",
  "IPO prospectus explained",
  "IPO application process India",
  "IPO application process USA",
  "how to check IPO allotment status",
  "mainboard IPO vs SME IPO",
  "biggest IPOs of 2026",
  "upcoming tech IPOs 2026",
  "direct listing vs IPO",
  "pre-IPO investing explained",
  "how to buy pre-IPO shares",
  "IPO oversubscription meaning",
  "anchor investors in an IPO meaning",
  "SpaceX IPO details",
  "OpenAI IPO news",
  "Anthropic IPO",
  "most anticipated IPOs 2026",
  "AI company IPOs to watch",
  "HKEX IPO",
  "screener for bipolar disorder",
  "screener upcoming ipo",
  "figma ipo stocks",
  "stocks that will benefit from spacex ipo",
];

export const portfolioKeywords: string[] = [
  "portfolio diversification strategy",
  "how to build an investment portfolio",
  "asset allocation strategy",
  "best stock portfolio tracker app",
  "how to start a stock portfolio",
  "how to protect your portfolio in a downturn",
  "HSBC Holdings stock price",
  "HSBC Holdings share price today",
  "HSBC Holdings stock forecast",
  "Is HSBC Holdings stock a good buy",
  "HSBC Holdings quarterly results",
  "Rolls-Royce Holdings stock price",
  "Rolls-Royce Holdings share price today",
  "Rolls-Royce Holdings stock forecast",
  "Is Rolls-Royce Holdings stock a good buy",
  "Rolls-Royce Holdings quarterly results",
  "yahoo my portfolio stocks list",
];

export const indiaKeywords: string[] = [
  "what is Nifty 50",
  "what is Sensex",
  "how many stock exchanges are there in India",
  "stock market timing in India",
  "how to open a demat account",
  "stock market news India today",
  "how to invest in US stocks from India",
  "investment guide for beginners in India",
  "best trading app in India",
  "NSE vs BSE difference",
  "best defense stocks 2026",
  "State Bank of India stock price",
  "State Bank of India share price today",
  "State Bank of India stock forecast",
  "Is State Bank of India stock a good buy",
  "State Bank of India quarterly results",
  "State Bank of India",
  "India",
  "NSE",
  "Nifty 50",
  "Sensex",
  "demat account",
  "ai stocks in india",
  "copper stocks in india",
  "data center stocks in india",
  "defence stocks india",
  "ethanol stocks in india",
  "ev stocks in india",
  "india semiconductor stocks",
  "list of nifty 50 stocks",
  "nifty 50 stocks list",
  "nifty 100 stocks list",
  "semiconductor stocks in india",
  "0 debt stocks in india",
  "52 week high stocks nse",
  "52 week low stocks nse",
  "52 week low stocks nifty 50",
  "90 promoter holding penny stocks nse",
  "BSE",
];

export const usKeywords: string[] = [
  "what is the Dow Jones",
  "what is the S&P 500",
  "Nebius stock forecast",
  "British American Tobacco stock price",
  "British American Tobacco share price today",
  "British American Tobacco stock forecast",
  "Is British American Tobacco stock a good buy",
  "British American Tobacco quarterly results",
  "NYSE",
  "S&P 500",
  "Dow Jones",
  "dow jones stocks",
  "dow jones stocks market",
  "stocks for ruger american gen 2",
  "how much stocks in dow jones",
  "stocks in the dow jones industrial average",
  "stocks in the s&p 500",
  "stocks in dow jones",
  "stocks joining the s&p 500",
  "stocks s&p 500",
  "us stocks",
  "us stocks today",
  "us stocks news",
  "zerodha us stocks",
  "zerodha invest in us stocks",
  "what is Nasdaq",
  "difference between NYSE and NASDAQ",
  "NASDAQ",
  "Nasdaq Composite",
  "stocks in nasdaq",
  "stocks in nasdaq 100",
  "nasdaq stocks",
];

export const ukKeywords: string[] = [
  "what is FTSE 100",
  "stock market news UK today",
  "how to invest in the LSE",
  "London Stock Exchange (LSE)",
  "FTSE 100",
  "FTSE 250",
  "FTSE Bursa Malaysia KLCI",
];

export const keywordGroups: { id: string; title: string; keywords: string[] }[] = [
  { id: "screener", title: "Stock screening & scanners", keywords: screenerKeywords },
  { id: "stocks", title: "Stocks, prices & forecasts", keywords: stocksKeywords },
  { id: "learn", title: "Investing & trading basics", keywords: learnKeywords },
  { id: "options", title: "Options, futures & derivatives", keywords: optionsKeywords },
  { id: "calendar", title: "Earnings, dividends & market calendar", keywords: calendarKeywords },
  { id: "ipo", title: "IPOs & new listings", keywords: ipoKeywords },
  { id: "portfolio", title: "Portfolio, watchlists & diversification", keywords: portfolioKeywords },
  { id: "india", title: "India: NSE, BSE, Nifty & Sensex", keywords: indiaKeywords },
  { id: "us", title: "US: NYSE, Nasdaq, Dow & S&P 500", keywords: usKeywords },
  { id: "uk", title: "UK: LSE & FTSE 100", keywords: ukKeywords },
];

export const exchangeKeywords: Record<string, string[]> = {
  NSE: indiaKeywords,
  BSE: indiaKeywords,
  NYSE: usKeywords,
  NASDAQ: usKeywords,
  LSE: ukKeywords,
};

/** Comma-joined keyword meta string, capped so the tag stays a sane length. */
export function metaKeywords(...lists: string[][]): string {
  const seen = new Set<string>();
  const picked: string[] = [];
  for (const list of lists) {
    for (const k of list) {
      const key = k.toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      picked.push(k);
      if (picked.length >= 60) return picked.join(", ");
    }
  }
  return picked.join(", ");
}
