import { jsonLd } from "@/lib/seo/json-ld";
import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { Shell } from "@/components/ds/Shell";
import { StockTable } from "@/components/ds/StockTable";
import { STOCKS } from "@/lib/deepscreen/stocks";
import { analyze } from "@/lib/deepscreen/metrics";
import { findRanking } from "@/lib/seo/content";
import { exchangeKeywords, metaKeywords, screenerKeywords, stocksKeywords } from "@/lib/seo/keywords";
const BASE = "https://deepscreen.online";
export const Route = createFileRoute("/best/$slug")({ staticData: { sitemap: true }, loader: ({ params }) => { const ranking = findRanking(params.slug); if (!ranking) throw notFound(); return { ranking }; }, head: ({ loaderData }) => { if (!loaderData) return {}; const r = loaderData.ranking; const url = `${BASE}/best/${r.slug}`; return { meta: [{ title: `${r.title} Across Global Markets | DeepScreen` }, { name: "description", content: r.description }, { name: "keywords", content: metaKeywords([r.title, `${r.title} ranking`, "best stocks by fundamentals", "fundamental stock rankings"], r.exchange ? (exchangeKeywords[r.exchange] ?? []) : [], stocksKeywords, screenerKeywords) }, { property: "og:title", content: r.title }, { property: "og:description", content: r.description }, { property: "og:type", content: "website" }, { property: "og:url", content: url }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: url }], scripts: [{ type: "application/ld+json", children: jsonLd({ "@context": "https://schema.org", "@type": "CollectionPage", name: r.title, description: r.description, url }) }] }; }, component: RankingPage });
function RankingPage() { const { ranking } = Route.useLoaderData(); const universe = ranking.exchange === "US" ? STOCKS.filter(s => s.exchange === "NYSE" || s.exchange === "NASDAQ") : ranking.exchange ? STOCKS.filter(s => s.exchange === ranking.exchange) : STOCKS; const stocks = [...universe].sort((a,b) => ranking.sort === "score" ? analyze(b).score-analyze(a).score : ranking.sort === "pe" ? a.fundamentals.pe-b.fundamentals.pe : b.fundamentals[ranking.sort]-a.fundamentals[ranking.sort]).slice(0,25); return <Shell><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><nav className="text-xs text-muted-foreground"><Link to="/">Home</Link> {" / "}Best stocks</nav><h1 className="mt-4 text-3xl font-bold">{ranking.title}</h1><p className="mt-3 max-w-3xl text-sm leading-relaxed text-muted-foreground">{ranking.answer}</p><p className="mt-3 text-xs text-muted-foreground"><time dateTime="2026-09-14">Last updated September 14, 2026</time></p><div className="mt-8"><StockTable stocks={stocks}/></div><p className="mt-5 text-xs text-muted-foreground">Rankings use available live data where possible and modeled estimates otherwise. They are not investment advice.</p></main></Shell>; }
