import { createFileRoute } from "@tanstack/react-router";
import { Shell } from "@/components/ds/Shell";
import { EXCHANGES } from "@/lib/deepscreen/exchanges";
import { resourceHead } from "@/lib/seo/discovery";

export const Route = createFileRoute("/press")({
  staticData: { sitemap: true },
  head: () => resourceHead("/press", "DeepScreen Press & Research Resources", "A factual overview of DeepScreen, its supported markets and resources for journalists and educators.", ["DeepScreen press", "DeepScreen media", "stock research resources", "financial research platform", "fundamental analysis platform", "stock screening platform", "stock market research tools", "investment research tools"]),
  component: Press,
});

function Press() {
  return <Shell><article className="mx-auto max-w-4xl space-y-8 px-4 py-10"><header><p className="text-sm text-primary">For journalists, educators and research partners</p><h1 className="mt-2 text-3xl font-bold">DeepScreen press and research resources</h1><p className="mt-4 text-muted-foreground">DeepScreen is a stock research platform covering supported listings across India, the United States and the United Kingdom.</p></header><section><h2 className="text-xl font-semibold">Product facts</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div className="rounded-lg border border-border p-4"><dt className="font-semibold">Website</dt><dd className="mt-2 text-muted-foreground">deepscreen.online</dd></div><div className="rounded-lg border border-border p-4"><dt className="font-semibold">Exchange directories</dt><dd className="mt-2 text-muted-foreground">{EXCHANGES.map((exchange) => exchange.code).join(", ")}</dd></div><div className="rounded-lg border border-border p-4"><dt className="font-semibold">Research approach</dt><dd className="mt-2 text-muted-foreground">Documented fundamental research methodology</dd></div><div className="rounded-lg border border-border p-4"><dt className="font-semibold">Editorial principle</dt><dd className="mt-2 text-muted-foreground">Research output is educational and should be checked against primary sources.</dd></div></dl></section><section><h2 className="text-xl font-semibold">Resources</h2><ul className="mt-4 list-disc space-y-3 pl-5 text-sm"><li><a className="text-primary underline" href="/research-checklist">Fundamental research checklist</a></li><li><a className="text-primary underline" href="/methodology">Methodology</a></li><li><a className="text-primary underline" href="/answers">Research questions and answers</a></li></ul></section><section><h2 className="text-xl font-semibold">Contact</h2><p className="mt-3 text-sm text-muted-foreground">For factual corrections or media enquiries, email <a className="text-primary underline" href="mailto:deepscreen.online@outlook.com">deepscreen.online@outlook.com</a>.</p></section></article></Shell>;
}
