import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { Shell } from "@/components/ds/Shell";
import { StockTable } from "@/components/ds/StockTable";
import { getExchange } from "@/lib/deepscreen/exchanges";
import { SECTORS, stocksByExchange } from "@/lib/deepscreen/stocks";
import { analyze } from "@/lib/deepscreen/metrics";
import { exchangeKeywords, metaKeywords, screenerKeywords, stocksKeywords } from "@/lib/seo/keywords";
const BASE = "https://deepscreen.online";
export const Route = createFileRoute("/sector/$exchange/$sector")({ staticData: { sitemap: true }, loader: ({ params }) => { const exchange = getExchange(params.exchange); const sector = SECTORS.find(s => s.toLowerCase().replaceAll(" ", "-") === params.sector.toLowerCase()); if (!exchange || !sector) throw notFound(); const stocks = stocksByExchange(exchange.code).filter(s => s.sector === sector).sort((a,b) => analyze(b).score-analyze(a).score); if (!stocks.length) throw notFound(); return { exchange, sector, stocks }; }, head: ({ loaderData }) => { if (!loaderData) return {}; const { exchange, sector, stocks } = loaderData; const url = `${BASE}/sector/${exchange.code}/${sector.toLowerCase().replaceAll(" ", "-")}`; const title = `${exchange.code} ${sector} Stocks — Rankings & Ratios | DeepScreen`; const description = `Compare ${stocks.length} ${sector} stocks on ${exchange.code} by DeepScreen score, P/E, PEG, ROCE, market cap and price.`; return { meta: [{ title }, { name: "description", content: description }, { name: "keywords", content: metaKeywords([`${exchange.code} ${sector} stocks`, `best ${sector} stocks`, `${sector} stock screener`, `${sector} stock comparison`], exchangeKeywords[exchange.code] ?? [], stocksKeywords, screenerKeywords) }, { property: "og:title", content: title }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { property: "og:url", content: url }, { name: "twitter:card", content: "summary_large_image" }, { name: "twitter:title", content: title }, { name: "twitter:description", content: description }], links: [{ rel: "canonical", href: url }], scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${BASE}/` }, { "@type": "ListItem", position: 2, name: exchange.code, item: `${BASE}/exchange/${exchange.code}` }, { "@type": "ListItem", position: 3, name: sector, item: url }] }) }] }; }, component: SectorPage });
function SectorPage() { const { exchange, sector, stocks } = Route.useLoaderData(); return <Shell><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><nav className="text-xs text-muted-foreground"><Link to="/">Home</Link> {" / "}<Link to="/exchange/$code" params={{ code: exchange.code }}>{exchange.code}</Link> {" / "}{sector}</nav><h1 className="mt-4 text-3xl font-bold">{exchange.code} {sector} stocks</h1><p className="mt-3 max-w-3xl text-sm text-muted-foreground">Compare {stocks.length} listed {sector.toLowerCase()} companies using DeepScreen’s 13-factor quality-and-value model. Use the ranking as a research shortlist, then review filings and sector-specific risks.</p><div className="mt-8"><StockTable stocks={stocks}/></div></main></Shell>; }
