export const ANSWERS_REVIEWED = "2026-09-18";

export const ANSWERS = [
  { id: "what-is-deepscreen", question: "What is DeepScreen?", answer: "DeepScreen is a research platform for supported listings across NSE, BSE, NYSE, Nasdaq and LSE. It combines searchable company research with educational explanations and a documented methodology.", href: "/methodology", label: "Read the methodology" },
  { id: "markets", question: "Which markets does DeepScreen cover?", answer: "DeepScreen covers supported listings on NSE and BSE in India, NYSE and Nasdaq in the United States, and LSE in the United Kingdom.", href: "/", label: "Browse the directories" },
  { id: "free-access", question: "Can I use DeepScreen for free?", answer: "Company search and educational guides are available without a paid subscription. Check the pricing page for current plan details and feature availability.", href: "/pricing", label: "Compare plans" },
  { id: "investment-advice", question: "Does DeepScreen provide investment advice?", answer: "No. DeepScreen provides research tools and educational explanations. Model output is not personalized advice, a forecast or a guarantee of returns.", href: "/terms", label: "Read the terms" },
  { id: "research", question: "How do I start fundamental research?", answer: "Start with the business model and primary disclosures, then compare consistent periods for earnings, cash flow, debt and valuation. Record assumptions and unresolved questions before drawing conclusions.", href: "/research-checklist", label: "Use the research checklist" },
  { id: "agent-access", question: "Can an AI assistant access DeepScreen resources?", answer: "Public educational resources can be linked and quoted with their limitations. Use the answers page, methodology and research checklist as the authoritative context for explanations.", href: "/developers", label: "Read developer guidance" },
  { id: "pe-ratio", question: "What is a P/E ratio?", answer: "P/E is share price divided by earnings per share. It compares a company's market price with a unit of annual earnings and should be interpreted with growth, cyclicality, profitability and sector context.", href: "/learn/pe-ratio-explained", label: "Read the P/E guide" },
  { id: "how-score", question: "How does DeepScreen score a stock?", answer: "DeepScreen combines valuation, growth, capital efficiency, leverage and shareholder-distribution factors into its documented 13-factor analytical model. The methodology explains the inputs, weighting and limitations.", href: "/methodology", label: "Read the methodology" },
  { id: "missing-data", question: "What happens when financial data is unavailable?", answer: "A missing provider figure should not be replaced with an invented value. DeepScreen distinguishes unavailable or insufficient provider data from analytical model outputs.", href: "/data-sources", label: "Read data-source notes" },
  { id: "compare-stocks", question: "How can I compare two companies?", answer: "Compare consistent measures such as earnings, cash flow, debt, valuation and returns across comparable periods and business models, then verify material figures against company disclosures.", href: "/compare", label: "Open company comparisons" },
  { id: "options", question: "Where can I learn about options strategies?", answer: "DeepScreen's options area explains strategy construction, payoff, breakeven and risk, alongside a calculator for modelling assumptions and outcomes.", href: "/options", label: "Open the options lab" },
  { id: "calendar", question: "Where can I find market and economic events?", answer: "DeepScreen provides an economic calendar for macro releases and market events, plus company-related calendar tools where available. Time-sensitive entries should be checked on the current calendar page.", href: "/calendar", label: "Open the calendar" },
  { id: "ipo", question: "Where can I find IPO information?", answer: "DeepScreen's IPO page provides the tracked pipeline and available offering details. Current status and dates should be verified against the relevant issuer or exchange disclosure.", href: "/ipo", label: "Open the IPO calendar" },
] as const;

export const HOME_ANSWERS = ANSWERS.slice(0, 4);
