import test from 'node:test';
import assert from 'node:assert/strict';
import { allocations, exportCsv, importCsv, parseCsv, readBackup, validSource } from '../src/lib/research/desk.ts';
const csv='market,symbol,quantity,average_cost,currency,name,thesis\nNSE,ABC,10,20,INR,"Example, Ltd","First line\nSecond line"';
test('quoted CSV supports commas and newlines and round trips notes',()=>{const entries=importCsv(csv);assert.equal(entries[0]?.name,'Example, Ltd');assert.equal(entries[0]?.thesis,'First line\nSecond line');assert.deepEqual(importCsv(exportCsv(entries),entries[0]!.updatedAt),entries);});
test('rejects invalid quantities, malformed quotes, dates and missing columns',()=>{assert.throws(()=>importCsv(csv.replace(',10,',',-10,')));assert.throws(()=>parseCsv('"unclosed'));assert.throws(()=>importCsv('symbol\nAAPL'));assert.throws(()=>importCsv('market,symbol,quantity,average_cost,currency,review_date\nNSE,ABC,1,2,INR,2026-02-30'));});
test('spreadsheet formulas are escaped while research text round trips',()=>{const e=importCsv(csv);e[0]!.thesis='=HYPERLINK("https://example.com")';const output=exportCsv(e);assert.ok(output.includes("'=HYPERLINK"));assert.equal(importCsv(output)[0]?.thesis,e[0]?.thesis);});
test('allocation keeps currencies separate and excludes watch-only entries',()=>{const e=importCsv('market,symbol,quantity,average_cost,currency\nNSE,A,10,20,INR\nNSE,B,5,40,INR\nNYSE,C,1,100,USD\nNSE,D,0,100,INR');const groups=allocations(e);assert.equal(groups.length,2);assert.equal(groups[0]?.total,400);assert.equal(groups[0]?.holdings[0]?.weight,50);assert.equal(groups[1]?.total,100);});
test('backup validates version, source URLs, duplicate IDs and numeric types',()=>{const e=importCsv(csv);assert.deepEqual(readBackup(JSON.stringify({version:1,entries:e})),e);assert.throws(()=>readBackup(JSON.stringify({version:2,entries:e})));assert.throws(()=>readBackup(JSON.stringify({version:1,entries:[e[0],e[0]]})));e[0]!.sources=['javascript:alert(1)'];assert.throws(()=>readBackup(JSON.stringify({version:1,entries:e})));assert.equal(validSource('https://example.com/report.pdf'),true);assert.equal(validSource('https://user:password@example.com'),false);});

test('tiny fractional holdings survive CSV export and import',()=>{const e=importCsv(csv);e[0]!.quantity=0.0000001;assert.equal(importCsv(exportCsv(e))[0]?.quantity,0.0000001);});
