/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnswersRouteImport } from './routes/answers'
import { Route as AnswersDotssmlRouteImport } from './routes/answers[.]ssml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as IpoRouteImport } from './routes/ipo'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PressRouteImport } from './routes/press'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResearchChecklistRouteImport } from './routes/research-checklist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BestSlugRouteImport } from './routes/best.$slug'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as ExchangeCodeRouteImport } from './routes/exchange.$code'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as OptionsStrategySlugRouteImport } from './routes/options-strategy.$slug'
import { Route as OptionsIndexRouteImport } from './routes/options.index'
import { Route as OptionsSlugRouteImport } from './routes/options.$slug'
import { Route as RatiosIndexRouteImport } from './routes/ratios.index'
import { Route as RatiosSlugRouteImport } from './routes/ratios.$slug'
import { Route as SitemapsChar123nameChar125DotxmlRouteImport } from './routes/sitemaps.{$name}[.]xml'
import { Route as ApiPublicCashfreeWebhookRouteImport } from './routes/api/public/cashfree-webhook'
import { Route as ApiV1ResourceRouteImport } from './routes/api.v1.$resource'
import { Route as SectorExchangeSectorRouteImport } from './routes/sector.$exchange.$sector'
import { Route as StockExchangeSymbolRouteImport } from './routes/stock.$exchange.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswersRoute = AnswersRouteImport.update({
  id: '/answers',
  path: '/answers',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswersDotssmlRoute = AnswersDotssmlRouteImport.update({
  id: '/answers.ssml',
  path: '/answers.ssml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoRoute = IpoRouteImport.update({
  id: '/ipo',
  path: '/ipo',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchChecklistRoute = ResearchChecklistRouteImport.update({
  id: '/research-checklist',
  path: '/research-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSlugRoute = BestSlugRouteImport.update({
  id: '/best/$slug',
  path: '/best/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeCodeRoute = ExchangeCodeRouteImport.update({
  id: '/exchange/$code',
  path: '/exchange/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsStrategySlugRoute = OptionsStrategySlugRouteImport.update({
  id: '/options-strategy/$slug',
  path: '/options-strategy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexRoute = OptionsIndexRouteImport.update({
  id: '/options/',
  path: '/options/',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsSlugRoute = OptionsSlugRouteImport.update({
  id: '/options/$slug',
  path: '/options/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RatiosIndexRoute = RatiosIndexRouteImport.update({
  id: '/ratios/',
  path: '/ratios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatiosSlugRoute = RatiosSlugRouteImport.update({
  id: '/ratios/$slug',
  path: '/ratios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsChar123nameChar125DotxmlRoute =
  SitemapsChar123nameChar125DotxmlRouteImport.update({
    id: '/sitemaps/{$name}.xml',
    path: '/sitemaps/{$name}.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCashfreeWebhookRoute =
  ApiPublicCashfreeWebhookRouteImport.update({
    id: '/api/public/cashfree-webhook',
    path: '/api/public/cashfree-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ResourceRoute = ApiV1ResourceRouteImport.update({
  id: '/api/v1/$resource',
  path: '/api/v1/$resource',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorExchangeSectorRoute = SectorExchangeSectorRouteImport.update({
  id: '/sector/$exchange/$sector',
  path: '/sector/$exchange/$sector',
  getParentRoute: () => rootRouteImport,
} as any)
const StockExchangeSymbolRoute = StockExchangeSymbolRouteImport.update({
  id: '/stock/$exchange/$symbol',
  path: '/stock/$exchange/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/answers': typeof AnswersRoute
  '/answers.ssml': typeof AnswersDotssmlRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/data-sources': typeof DataSourcesRoute
  '/developers': typeof DevelopersRoute
  '/ipo': typeof IpoRoute
  '/methodology': typeof MethodologyRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/portfolio': typeof PortfolioRoute
  '/press': typeof PressRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/research-checklist': typeof ResearchChecklistRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/best/$slug': typeof BestSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/exchange/$code': typeof ExchangeCodeRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/options-strategy/$slug': typeof OptionsStrategySlugRoute
  '/options/$slug': typeof OptionsSlugRoute
  '/ratios/$slug': typeof RatiosSlugRoute
  '/sitemaps/{$name}.xml': typeof SitemapsChar123nameChar125DotxmlRoute
  '/learn/': typeof LearnIndexRoute
  '/options/': typeof OptionsIndexRoute
  '/ratios/': typeof RatiosIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/v1/$resource': typeof ApiV1ResourceRoute
  '/sector/$exchange/$sector': typeof SectorExchangeSectorRoute
  '/stock/$exchange/$symbol': typeof StockExchangeSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/answers': typeof AnswersRoute
  '/answers.ssml': typeof AnswersDotssmlRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/data-sources': typeof DataSourcesRoute
  '/developers': typeof DevelopersRoute
  '/ipo': typeof IpoRoute
  '/methodology': typeof MethodologyRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/portfolio': typeof PortfolioRoute
  '/press': typeof PressRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/research-checklist': typeof ResearchChecklistRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/best/$slug': typeof BestSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/exchange/$code': typeof ExchangeCodeRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/options-strategy/$slug': typeof OptionsStrategySlugRoute
  '/options/$slug': typeof OptionsSlugRoute
  '/ratios/$slug': typeof RatiosSlugRoute
  '/sitemaps/{$name}.xml': typeof SitemapsChar123nameChar125DotxmlRoute
  '/learn': typeof LearnIndexRoute
  '/options': typeof OptionsIndexRoute
  '/ratios': typeof RatiosIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/v1/$resource': typeof ApiV1ResourceRoute
  '/sector/$exchange/$sector': typeof SectorExchangeSectorRoute
  '/stock/$exchange/$symbol': typeof StockExchangeSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/answers': typeof AnswersRoute
  '/answers.ssml': typeof AnswersDotssmlRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/data-sources': typeof DataSourcesRoute
  '/developers': typeof DevelopersRoute
  '/ipo': typeof IpoRoute
  '/methodology': typeof MethodologyRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/portfolio': typeof PortfolioRoute
  '/press': typeof PressRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/research-checklist': typeof ResearchChecklistRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/best/$slug': typeof BestSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/exchange/$code': typeof ExchangeCodeRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/options-strategy/$slug': typeof OptionsStrategySlugRoute
  '/options/$slug': typeof OptionsSlugRoute
  '/ratios/$slug': typeof RatiosSlugRoute
  '/sitemaps/{$name}.xml': typeof SitemapsChar123nameChar125DotxmlRoute
  '/learn/': typeof LearnIndexRoute
  '/options/': typeof OptionsIndexRoute
  '/ratios/': typeof RatiosIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/v1/$resource': typeof ApiV1ResourceRoute
  '/sector/$exchange/$sector': typeof SectorExchangeSectorRoute
  '/stock/$exchange/$symbol': typeof StockExchangeSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/answers'
    | '/answers.ssml'
    | '/auth'
    | '/calendar'
    | '/contact'
    | '/data-sources'
    | '/developers'
    | '/ipo'
    | '/methodology'
    | '/openapi.json'
    | '/portfolio'
    | '/press'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/research-checklist'
    | '/sitemap.xml'
    | '/terms'
    | '/best/$slug'
    | '/compare/$slug'
    | '/exchange/$code'
    | '/learn/$slug'
    | '/options-strategy/$slug'
    | '/options/$slug'
    | '/ratios/$slug'
    | '/sitemaps/{$name}.xml'
    | '/learn/'
    | '/options/'
    | '/ratios/'
    | '/api/public/cashfree-webhook'
    | '/api/v1/$resource'
    | '/sector/$exchange/$sector'
    | '/stock/$exchange/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/answers'
    | '/answers.ssml'
    | '/auth'
    | '/calendar'
    | '/contact'
    | '/data-sources'
    | '/developers'
    | '/ipo'
    | '/methodology'
    | '/openapi.json'
    | '/portfolio'
    | '/press'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/research-checklist'
    | '/sitemap.xml'
    | '/terms'
    | '/best/$slug'
    | '/compare/$slug'
    | '/exchange/$code'
    | '/learn/$slug'
    | '/options-strategy/$slug'
    | '/options/$slug'
    | '/ratios/$slug'
    | '/sitemaps/{$name}.xml'
    | '/learn'
    | '/options'
    | '/ratios'
    | '/api/public/cashfree-webhook'
    | '/api/v1/$resource'
    | '/sector/$exchange/$sector'
    | '/stock/$exchange/$symbol'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/answers'
    | '/answers.ssml'
    | '/auth'
    | '/calendar'
    | '/contact'
    | '/data-sources'
    | '/developers'
    | '/ipo'
    | '/methodology'
    | '/openapi.json'
    | '/portfolio'
    | '/press'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/research-checklist'
    | '/sitemap.xml'
    | '/terms'
    | '/best/$slug'
    | '/compare/$slug'
    | '/exchange/$code'
    | '/learn/$slug'
    | '/options-strategy/$slug'
    | '/options/$slug'
    | '/ratios/$slug'
    | '/sitemaps/{$name}.xml'
    | '/learn/'
    | '/options/'
    | '/ratios/'
    | '/api/public/cashfree-webhook'
    | '/api/v1/$resource'
    | '/sector/$exchange/$sector'
    | '/stock/$exchange/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnswersRoute: typeof AnswersRoute
  AnswersDotssmlRoute: typeof AnswersDotssmlRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ContactRoute: typeof ContactRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DevelopersRoute: typeof DevelopersRoute
  IpoRoute: typeof IpoRoute
  MethodologyRoute: typeof MethodologyRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  PortfolioRoute: typeof PortfolioRoute
  PressRoute: typeof PressRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResearchChecklistRoute: typeof ResearchChecklistRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BestSlugRoute: typeof BestSlugRoute
  CompareSlugRoute: typeof CompareSlugRoute
  ExchangeCodeRoute: typeof ExchangeCodeRoute
  LearnSlugRoute: typeof LearnSlugRoute
  OptionsStrategySlugRoute: typeof OptionsStrategySlugRoute
  OptionsSlugRoute: typeof OptionsSlugRoute
  RatiosSlugRoute: typeof RatiosSlugRoute
  SitemapsChar123nameChar125DotxmlRoute: typeof SitemapsChar123nameChar125DotxmlRoute
  LearnIndexRoute: typeof LearnIndexRoute
  OptionsIndexRoute: typeof OptionsIndexRoute
  RatiosIndexRoute: typeof RatiosIndexRoute
  ApiPublicCashfreeWebhookRoute: typeof ApiPublicCashfreeWebhookRoute
  ApiV1ResourceRoute: typeof ApiV1ResourceRoute
  SectorExchangeSectorRoute: typeof SectorExchangeSectorRoute
  StockExchangeSymbolRoute: typeof StockExchangeSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answers': {
      id: '/answers'
      path: '/answers'
      fullPath: '/answers'
      preLoaderRoute: typeof AnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answers.ssml': {
      id: '/answers.ssml'
      path: '/answers.ssml'
      fullPath: '/answers.ssml'
      preLoaderRoute: typeof AnswersDotssmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo': {
      id: '/ipo'
      path: '/ipo'
      fullPath: '/ipo'
      preLoaderRoute: typeof IpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-checklist': {
      id: '/research-checklist'
      path: '/research-checklist'
      fullPath: '/research-checklist'
      preLoaderRoute: typeof ResearchChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best/$slug': {
      id: '/best/$slug'
      path: '/best/$slug'
      fullPath: '/best/$slug'
      preLoaderRoute: typeof BestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange/$code': {
      id: '/exchange/$code'
      path: '/exchange/$code'
      fullPath: '/exchange/$code'
      preLoaderRoute: typeof ExchangeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options-strategy/$slug': {
      id: '/options-strategy/$slug'
      path: '/options-strategy/$slug'
      fullPath: '/options-strategy/$slug'
      preLoaderRoute: typeof OptionsStrategySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/': {
      id: '/options/'
      path: '/options'
      fullPath: '/options/'
      preLoaderRoute: typeof OptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/$slug': {
      id: '/options/$slug'
      path: '/options/$slug'
      fullPath: '/options/$slug'
      preLoaderRoute: typeof OptionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratios/': {
      id: '/ratios/'
      path: '/ratios'
      fullPath: '/ratios/'
      preLoaderRoute: typeof RatiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratios/$slug': {
      id: '/ratios/$slug'
      path: '/ratios/$slug'
      fullPath: '/ratios/$slug'
      preLoaderRoute: typeof RatiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/{$name}.xml': {
      id: '/sitemaps/{$name}.xml'
      path: '/sitemaps/{$name}.xml'
      fullPath: '/sitemaps/{$name}.xml'
      preLoaderRoute: typeof SitemapsChar123nameChar125DotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cashfree-webhook': {
      id: '/api/public/cashfree-webhook'
      path: '/api/public/cashfree-webhook'
      fullPath: '/api/public/cashfree-webhook'
      preLoaderRoute: typeof ApiPublicCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$resource': {
      id: '/api/v1/$resource'
      path: '/api/v1/$resource'
      fullPath: '/api/v1/$resource'
      preLoaderRoute: typeof ApiV1ResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sector/$exchange/$sector': {
      id: '/sector/$exchange/$sector'
      path: '/sector/$exchange/$sector'
      fullPath: '/sector/$exchange/$sector'
      preLoaderRoute: typeof SectorExchangeSectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$exchange/$symbol': {
      id: '/stock/$exchange/$symbol'
      path: '/stock/$exchange/$symbol'
      fullPath: '/stock/$exchange/$symbol'
      preLoaderRoute: typeof StockExchangeSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnswersRoute: AnswersRoute,
  AnswersDotssmlRoute: AnswersDotssmlRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ContactRoute: ContactRoute,
  DataSourcesRoute: DataSourcesRoute,
  DevelopersRoute: DevelopersRoute,
  IpoRoute: IpoRoute,
  MethodologyRoute: MethodologyRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  PortfolioRoute: PortfolioRoute,
  PressRoute: PressRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResearchChecklistRoute: ResearchChecklistRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BestSlugRoute: BestSlugRoute,
  CompareSlugRoute: CompareSlugRoute,
  ExchangeCodeRoute: ExchangeCodeRoute,
  LearnSlugRoute: LearnSlugRoute,
  OptionsStrategySlugRoute: OptionsStrategySlugRoute,
  OptionsSlugRoute: OptionsSlugRoute,
  RatiosSlugRoute: RatiosSlugRoute,
  SitemapsChar123nameChar125DotxmlRoute: SitemapsChar123nameChar125DotxmlRoute,
  LearnIndexRoute: LearnIndexRoute,
  OptionsIndexRoute: OptionsIndexRoute,
  RatiosIndexRoute: RatiosIndexRoute,
  ApiPublicCashfreeWebhookRoute: ApiPublicCashfreeWebhookRoute,
  ApiV1ResourceRoute: ApiV1ResourceRoute,
  SectorExchangeSectorRoute: SectorExchangeSectorRoute,
  StockExchangeSymbolRoute: StockExchangeSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
