/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ExchangeCodeRouteImport } from './routes/exchange.$code'
import { Route as StockExchangeSymbolRouteImport } from './routes/stock.$exchange.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeCodeRoute = ExchangeCodeRouteImport.update({
  id: '/exchange/$code',
  path: '/exchange/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const StockExchangeSymbolRoute = StockExchangeSymbolRouteImport.update({
  id: '/stock/$exchange/$symbol',
  path: '/stock/$exchange/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/crypto': typeof CryptoRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/exchange/$code': typeof ExchangeCodeRoute
  '/stock/$exchange/$symbol': typeof StockExchangeSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/crypto': typeof CryptoRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/exchange/$code': typeof ExchangeCodeRoute
  '/stock/$exchange/$symbol': typeof StockExchangeSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/crypto': typeof CryptoRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/exchange/$code': typeof ExchangeCodeRoute
  '/stock/$exchange/$symbol': typeof StockExchangeSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/crypto'
    | '/portfolio'
    | '/pricing'
    | '/exchange/$code'
    | '/stock/$exchange/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/crypto'
    | '/portfolio'
    | '/pricing'
    | '/exchange/$code'
    | '/stock/$exchange/$symbol'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/crypto'
    | '/portfolio'
    | '/pricing'
    | '/exchange/$code'
    | '/stock/$exchange/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  CryptoRoute: typeof CryptoRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  ExchangeCodeRoute: typeof ExchangeCodeRoute
  StockExchangeSymbolRoute: typeof StockExchangeSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange/$code': {
      id: '/exchange/$code'
      path: '/exchange/$code'
      fullPath: '/exchange/$code'
      preLoaderRoute: typeof ExchangeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$exchange/$symbol': {
      id: '/stock/$exchange/$symbol'
      path: '/stock/$exchange/$symbol'
      fullPath: '/stock/$exchange/$symbol'
      preLoaderRoute: typeof StockExchangeSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  CryptoRoute: CryptoRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  ExchangeCodeRoute: ExchangeCodeRoute,
  StockExchangeSymbolRoute: StockExchangeSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
