/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IpoRouteImport } from './routes/ipo'
import { Route as OptionsRouteImport } from './routes/options'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ExchangeCodeRouteImport } from './routes/exchange.$code'
import { Route as ApiPublicCashfreeWebhookRouteImport } from './routes/api/public/cashfree-webhook'
import { Route as StockExchangeSymbolRouteImport } from './routes/stock.$exchange.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoRoute = IpoRouteImport.update({
  id: '/ipo',
  path: '/ipo',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsRoute = OptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeCodeRoute = ExchangeCodeRouteImport.update({
  id: '/exchange/$code',
  path: '/exchange/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCashfreeWebhookRoute =
  ApiPublicCashfreeWebhookRouteImport.update({
    id: '/api/public/cashfree-webhook',
    path: '/api/public/cashfree-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const StockExchangeSymbolRoute = StockExchangeSymbolRouteImport.update({
  id: '/stock/$exchange/$symbol',
  path: '/stock/$exchange/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/ipo': typeof IpoRoute
  '/options': typeof OptionsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/exchange/$code': typeof ExchangeCodeRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/stock/$exchange/$symbol': typeof StockExchangeSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/ipo': typeof IpoRoute
  '/options': typeof OptionsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/exchange/$code': typeof ExchangeCodeRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/stock/$exchange/$symbol': typeof StockExchangeSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/ipo': typeof IpoRoute
  '/options': typeof OptionsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/exchange/$code': typeof ExchangeCodeRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/stock/$exchange/$symbol': typeof StockExchangeSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/contact'
    | '/ipo'
    | '/options'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/exchange/$code'
    | '/api/public/cashfree-webhook'
    | '/stock/$exchange/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/contact'
    | '/ipo'
    | '/options'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/exchange/$code'
    | '/api/public/cashfree-webhook'
    | '/stock/$exchange/$symbol'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/contact'
    | '/ipo'
    | '/options'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/exchange/$code'
    | '/api/public/cashfree-webhook'
    | '/stock/$exchange/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ContactRoute: typeof ContactRoute
  IpoRoute: typeof IpoRoute
  OptionsRoute: typeof OptionsRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ExchangeCodeRoute: typeof ExchangeCodeRoute
  ApiPublicCashfreeWebhookRoute: typeof ApiPublicCashfreeWebhookRoute
  StockExchangeSymbolRoute: typeof StockExchangeSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo': {
      id: '/ipo'
      path: '/ipo'
      fullPath: '/ipo'
      preLoaderRoute: typeof IpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options': {
      id: '/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof OptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange/$code': {
      id: '/exchange/$code'
      path: '/exchange/$code'
      fullPath: '/exchange/$code'
      preLoaderRoute: typeof ExchangeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cashfree-webhook': {
      id: '/api/public/cashfree-webhook'
      path: '/api/public/cashfree-webhook'
      fullPath: '/api/public/cashfree-webhook'
      preLoaderRoute: typeof ApiPublicCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$exchange/$symbol': {
      id: '/stock/$exchange/$symbol'
      path: '/stock/$exchange/$symbol'
      fullPath: '/stock/$exchange/$symbol'
      preLoaderRoute: typeof StockExchangeSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ContactRoute: ContactRoute,
  IpoRoute: IpoRoute,
  OptionsRoute: OptionsRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ExchangeCodeRoute: ExchangeCodeRoute,
  ApiPublicCashfreeWebhookRoute: ApiPublicCashfreeWebhookRoute,
  StockExchangeSymbolRoute: StockExchangeSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
